.\" Copyright 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright 2024, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH ioctl_nsfs 2 2024-06-14 "Linux man-pages (unreleased)"
.SH NAME
ioctl_nsfs
\-
ioctl() operations for Linux namespaces
.SH SYNOPSIS
.nf
.BR "#include <linux/nsfs.h>" "  /* Definition of " NS_* " constants */"
.B #include <sys/ioctl.h>
.P
.BI "int ioctl(int " fd ", unsigned long " op ", ...);"
.fi
.SH DESCRIPTION
.SS Discovering namespace relationships
.TP
.BR NS_GET_USERNS (2const)
.TQ
.BR NS_GET_PARENT (2const)
.SS Discovering the namespace type
.TP
.BR NS_GET_NSTYPE (2const)
.SS Discovering the owner of a user namespace
.TP
.BR NS_GET_OWNER_UID (2const)
.SH ERRORS
.TP
.B ENOTTY
.I fd
does not refer to a
.IR /proc/ pid /ns/ *
file.
.SH STANDARDS
Linux.
.SH SEE ALSO
.BR ioctl (2),
.BR fstat (2),
.BR proc (5),
.BR namespaces (7)
