.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_vmstat 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/vmstat \- virtual memory statistics
.SH DESCRIPTION
.TP
.IR /proc/vmstat " (since Linux 2.6.0)"
This file displays various virtual memory statistics.
Each line of this file contains a single name-value pair,
delimited by white space.
Some lines are present only if the kernel was configured with
suitable options.
(In some cases, the options required for particular files have changed
across kernel versions, so they are not listed here.
Details can be found by consulting the kernel source code.)
The following fields may be present:
.\" FIXME We need explanations for each of the following fields...
.RS
.TP
.IR nr_free_pages " (since Linux 2.6.31)"
.\" commit d23ad42324cc4378132e51f2fc5c9ba6cbe75182
.TP
.IR nr_alloc_batch " (since Linux 3.12)"
.\" commit 81c0a2bb515fd4daae8cab64352877480792b515
.TP
.IR nr_inactive_anon " (since Linux 2.6.28)"
.\" commit 4f98a2fee8acdb4ac84545df98cccecfd130f8db
.TP
.IR nr_active_anon " (since Linux 2.6.28)"
.\" commit 4f98a2fee8acdb4ac84545df98cccecfd130f8db
.TP
.IR nr_inactive_file " (since Linux 2.6.28)"
.\" commit 4f98a2fee8acdb4ac84545df98cccecfd130f8db
.TP
.IR nr_active_file " (since Linux 2.6.28)"
.\" commit 4f98a2fee8acdb4ac84545df98cccecfd130f8db
.TP
.IR nr_unevictable " (since Linux 2.6.28)"
.\" commit 7b854121eb3e5ba0241882ff939e2c485228c9c5
.TP
.IR nr_mlock " (since Linux 2.6.28)"
.\" commit 5344b7e648980cc2ca613ec03a56a8222ff48820
.TP
.IR nr_anon_pages " (since Linux 2.6.18)"
.\" commit f3dbd34460ff54962d3e3244b6bcb7f5295356e6
.TP
.IR nr_mapped " (since Linux 2.6.0)"
.TP
.IR nr_file_pages " (since Linux 2.6.18)"
.\" commit 347ce434d57da80fd5809c0c836f206a50999c26
.TP
.IR nr_dirty " (since Linux 2.6.0)"
.TP
.IR nr_writeback " (since Linux 2.6.0)"
.TP
.IR nr_slab_reclaimable " (since Linux 2.6.19)"
.\" commit 972d1a7b140569084439a81265a0f15b74e924e0
.\" Linux 2.6.0 had nr_slab
.TP
.IR nr_slab_unreclaimable " (since Linux 2.6.19)"
.\" commit 972d1a7b140569084439a81265a0f15b74e924e0
.TP
.IR nr_page_table_pages " (since Linux 2.6.0)"
.TP
.IR nr_kernel_stack " (since Linux 2.6.32)"
.\" commit c6a7f5728a1db45d30df55a01adc130b4ab0327c
Amount of memory allocated to kernel stacks.
.TP
.IR nr_unstable " (since Linux 2.6.0)"
.TP
.IR nr_bounce " (since Linux 2.6.12)"
.\" commit edfbe2b0038723e5699ab22695ccd62b5542a5c1
.TP
.IR nr_vmscan_write " (since Linux 2.6.19)"
.\" commit e129b5c23c2b471d47f1c5d2b8b193fc2034af43
.TP
.IR nr_vmscan_immediate_reclaim " (since Linux 3.2)"
.\" commit 49ea7eb65e7c5060807fb9312b1ad4c3eab82e2c
.TP
.IR nr_writeback_temp " (since Linux 2.6.26)"
.\" commit fc3ba692a4d19019387c5acaea63131f9eab05dd
.TP
.IR nr_isolated_anon " (since Linux 2.6.32)"
.\" commit a731286de62294b63d8ceb3c5914ac52cc17e690
.TP
.IR nr_isolated_file " (since Linux 2.6.32)"
.\" commit a731286de62294b63d8ceb3c5914ac52cc17e690
.TP
.IR nr_shmem " (since Linux 2.6.32)"
.\" commit 4b02108ac1b3354a22b0d83c684797692efdc395
Pages used by shmem and
.BR tmpfs (5).
.TP
.IR nr_dirtied " (since Linux 2.6.37)"
.\" commit ea941f0e2a8c02ae876cd73deb4e1557248f258c
.TP
.IR nr_written " (since Linux 2.6.37)"
.\" commit ea941f0e2a8c02ae876cd73deb4e1557248f258c
.TP
.IR nr_pages_scanned " (since Linux 3.17)"
.\" commit 0d5d823ab4e608ec7b52ac4410de4cb74bbe0edd
.TP
.IR numa_hit " (since Linux 2.6.18)"
.\" commit ca889e6c45e0b112cb2ca9d35afc66297519b5d5
.\" Present only if the kernel was configured with
.\" .BR CONFIG_NUMA .
.TP
.IR numa_miss " (since Linux 2.6.18)"
.\" commit ca889e6c45e0b112cb2ca9d35afc66297519b5d5
.\" Present only if the kernel was configured with
.\" .BR CONFIG_NUMA .
.TP
.IR numa_foreign " (since Linux 2.6.18)"
.\" commit ca889e6c45e0b112cb2ca9d35afc66297519b5d5
.\" Present only if the kernel was configured with
.\" .BR CONFIG_NUMA .
.TP
.IR numa_interleave " (since Linux 2.6.18)"
.\" commit ca889e6c45e0b112cb2ca9d35afc66297519b5d5
.\" Present only if the kernel was configured with
.\" .BR CONFIG_NUMA .
.TP
.IR numa_local " (since Linux 2.6.18)"
.\" commit ca889e6c45e0b112cb2ca9d35afc66297519b5d5
.\" Present only if the kernel was configured with
.\" .BR CONFIG_NUMA .
.TP
.IR numa_other " (since Linux 2.6.18)"
.\" commit ca889e6c45e0b112cb2ca9d35afc66297519b5d5
.\" Present only if the kernel was configured with
.\" .BR CONFIG_NUMA .
.TP
.IR workingset_refault " (since Linux 3.15)"
.\" commit a528910e12ec7ee203095eb1711468a66b9b60b0
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR workingset_activate " (since Linux 3.15)"
.\" commit a528910e12ec7ee203095eb1711468a66b9b60b0
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR workingset_nodereclaim " (since Linux 3.15)"
.\" commit 449dd6984d0e47643c04c807f609dd56d48d5bcc
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR nr_anon_transparent_hugepages " (since Linux 2.6.38)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR nr_free_cma " (since Linux 3.7)"
.\" commit d1ce749a0db12202b711d1aba1d29e823034648d
Number of free CMA (Contiguous Memory Allocator) pages.
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR nr_dirty_threshold " (since Linux 2.6.37)"
.\" commit 79da826aee6a10902ef411bc65864bd02102fa83
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR nr_dirty_background_threshold " (since Linux 2.6.37)"
.\" commit 79da826aee6a10902ef411bc65864bd02102fa83
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgpgin " (since Linux 2.6.0)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgpgout " (since Linux 2.6.0)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pswpin " (since Linux 2.6.0)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pswpout " (since Linux 2.6.0)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgalloc_dma " (since Linux 2.6.5)"
.\" Linux 2.6.0 had pgalloc
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgalloc_dma32 " (since Linux 2.6.16)"
.\" commit 9328b8faae922e52073785ed6c1eaa8565648a0e
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgalloc_normal " (since Linux 2.6.5)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgalloc_high " (since Linux 2.6.5)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_HIGHMEM .
.TP
.IR pgalloc_movable " (since Linux 2.6.23)"
.\" commit 2a1e274acf0b1c192face19a4be7c12d4503eaaf
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgfree " (since Linux 2.6.0)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgactivate " (since Linux 2.6.0)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgdeactivate " (since Linux 2.6.0)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgfault " (since Linux 2.6.0)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgmajfault " (since Linux 2.6.0)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgrefill_dma " (since Linux 2.6.5)"
.\" Linux 2.6.0 had pgrefill
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgrefill_dma32 " (since Linux 2.6.16)"
.\" commit 9328b8faae922e52073785ed6c1eaa8565648a0e
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgrefill_normal " (since Linux 2.6.5)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgrefill_high " (since Linux 2.6.5)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_HIGHMEM .
.TP
.IR pgrefill_movable " (since Linux 2.6.23)"
.\" commit 2a1e274acf0b1c192face19a4be7c12d4503eaaf
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.\" Formerly there were
.\"     pgsteal_high
.\"     pgsteal_normal
.\"     pgsteal_dma32
.\"     pgsteal_dma
.\" These were split out into pgsteal_kswapd* and pgsteal_direct*
.\" in commit 904249aa68010c8e223263c922fcbb840a3f42e4
.TP
.IR pgsteal_kswapd_dma " (since Linux 3.4)"
.\" commit 904249aa68010c8e223263c922fcbb840a3f42e4
.\" Linux 2.6.0 had pgsteal
.\" Present only if the kernel was configured with
.\" .\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgsteal_kswapd_dma32 " (since Linux 3.4)"
.\" commit 904249aa68010c8e223263c922fcbb840a3f42e4
.\" commit 9328b8faae922e52073785ed6c1eaa8565648a0e
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgsteal_kswapd_normal " (since Linux 3.4)"
.\" commit 904249aa68010c8e223263c922fcbb840a3f42e4
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgsteal_kswapd_high " (since Linux 3.4)"
.\" commit 904249aa68010c8e223263c922fcbb840a3f42e4
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_HIGHMEM .
.TP
.IR pgsteal_kswapd_movable " (since Linux 3.4)"
.\" commit 904249aa68010c8e223263c922fcbb840a3f42e4
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.I pgsteal_direct_dma
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgsteal_direct_dma32 " (since Linux 3.4)"
.\" commit 904249aa68010c8e223263c922fcbb840a3f42e4
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgsteal_direct_normal " (since Linux 3.4)"
.\" commit 904249aa68010c8e223263c922fcbb840a3f42e4
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgsteal_direct_high " (since Linux 3.4)"
.\" commit 904249aa68010c8e223263c922fcbb840a3f42e4
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_HIGHMEM .
.TP
.IR pgsteal_direct_movable " (since Linux 2.6.23)"
.\" commit 2a1e274acf0b1c192face19a4be7c12d4503eaaf
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.I pgscan_kswapd_dma
.\" Linux 2.6.0 had pgscan
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgscan_kswapd_dma32 " (since Linux 2.6.16)"
.\" commit 9328b8faae922e52073785ed6c1eaa8565648a0e
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgscan_kswapd_normal " (since Linux 2.6.5)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.I pgscan_kswapd_high
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_HIGHMEM .
.TP
.IR pgscan_kswapd_movable " (since Linux 2.6.23)"
.\" commit 2a1e274acf0b1c192face19a4be7c12d4503eaaf
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.I pgscan_direct_dma
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgscan_direct_dma32 " (since Linux 2.6.16)"
.\" commit 9328b8faae922e52073785ed6c1eaa8565648a0e
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.I pgscan_direct_normal
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.I pgscan_direct_high
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_HIGHMEM .
.TP
.IR pgscan_direct_movable " (since Linux 2.6.23)"
.\" commit 2a1e274acf0b1c192face19a4be7c12d4503eaaf
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgscan_direct_throttle " (since Linux 3.6)"
.\" commit 68243e76ee343d63c6cf76978588a885951e2818
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR zone_reclaim_failed " (since linux 2.6.31)"
.\" commit 24cf72518c79cdcda486ed26074ff8151291cf65
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_NUMA .
.TP
.IR pginodesteal " (since linux 2.6.0)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR slabs_scanned " (since linux 2.6.5)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR kswapd_inodesteal " (since linux 2.6.0)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR kswapd_low_wmark_hit_quickly " (since Linux 2.6.33)"
.\" commit bb3ab596832b920c703d1aea1ce76d69c0f71fb7
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR kswapd_high_wmark_hit_quickly " (since Linux 2.6.33)"
.\" commit bb3ab596832b920c703d1aea1ce76d69c0f71fb7
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pageoutrun " (since Linux 2.6.0)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR allocstall " (since Linux 2.6.0)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR pgrotated " (since Linux 2.6.0)"
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR drop_pagecache " (since Linux 3.15)"
.\" commit 5509a5d27b971a90b940e148ca9ca53312e4fa7a
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR drop_slab " (since Linux 3.15)"
.\" commit 5509a5d27b971a90b940e148ca9ca53312e4fa7a
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR numa_pte_updates " (since Linux 3.8)"
.\" commit 03c5a6e16322c997bf8f264851bfa3f532ad515f
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_NUMA_BALANCING .
.TP
.IR numa_huge_pte_updates " (since Linux 3.13)"
.\" commit 72403b4a0fbdf433c1fe0127e49864658f6f6468
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_NUMA_BALANCING .
.TP
.IR numa_hint_faults " (since Linux 3.8)"
.\" commit 03c5a6e16322c997bf8f264851bfa3f532ad515f
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_NUMA_BALANCING .
.TP
.IR numa_hint_faults_local " (since Linux 3.8)"
.\" commit 03c5a6e16322c997bf8f264851bfa3f532ad515f
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_NUMA_BALANCING .
.TP
.IR numa_pages_migrated " (since Linux 3.8)"
.\" commit 03c5a6e16322c997bf8f264851bfa3f532ad515f
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_NUMA_BALANCING
.\" and
.\" .BR CONFIG_NUMA_BALANCING .
.TP
.IR pgmigrate_success " (since Linux 3.8)"
.\" commit 5647bc293ab15f66a7b1cda850c5e9d162a6c7c2
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_MIGRATION .
.TP
.IR pgmigrate_fail " (since Linux 3.8)"
.\" commit 5647bc293ab15f66a7b1cda850c5e9d162a6c7c2
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_MIGRATION .
.TP
.IR compact_migrate_scanned " (since Linux 3.8)"
.\" commit 397487db696cae0b026a474a5cd66f4e372995e6
.\" Linux 3.8 dropped compact_blocks_moved, compact_pages_moved, and
.\"           compact_pagemigrate_failed
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_COMPACTION .
.TP
.IR compact_free_scanned " (since Linux 3.8)"
.\" commit 397487db696cae0b026a474a5cd66f4e372995e6
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_COMPACTION .
.TP
.IR compact_isolated " (since Linux 3.8)"
.\" commit 397487db696cae0b026a474a5cd66f4e372995e6
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_COMPACTION .
.TP
.IR compact_stall " (since Linux 2.6.35)"
.\" commit 56de7263fcf3eb10c8dcdf8d59a9cec831795f3f
See the kernel source file
.IR Documentation/admin\-guide/mm/transhuge.rst .
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_COMPACTION .
.TP
.IR compact_fail " (since Linux 2.6.35)"
.\" commit 56de7263fcf3eb10c8dcdf8d59a9cec831795f3f
See the kernel source file
.IR Documentation/admin\-guide/mm/transhuge.rst .
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_COMPACTION .
.TP
.IR compact_success " (since Linux 2.6.35)"
.\" commit 56de7263fcf3eb10c8dcdf8d59a9cec831795f3f
See the kernel source file
.IR Documentation/admin\-guide/mm/transhuge.rst .
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_COMPACTION .
.TP
.IR htlb_buddy_alloc_success " (since Linux 2.6.26)"
.\" commit 3b1163006332302117b1b2acf226d4014ff46525
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_HUGETLB_PAGE .
.TP
.IR htlb_buddy_alloc_fail " (since Linux 2.6.26)"
.\" commit 3b1163006332302117b1b2acf226d4014ff46525
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_HUGETLB_PAGE .
.TP
.IR unevictable_pgs_culled " (since Linux 2.6.28)"
.\" commit bbfd28eee9fbd73e780b19beb3dc562befbb94fa
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR unevictable_pgs_scanned " (since Linux 2.6.28)"
.\" commit bbfd28eee9fbd73e780b19beb3dc562befbb94fa
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR unevictable_pgs_rescued " (since Linux 2.6.28)"
.\" commit bbfd28eee9fbd73e780b19beb3dc562befbb94fa
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR unevictable_pgs_mlocked " (since Linux 2.6.28)"
.\" commit 5344b7e648980cc2ca613ec03a56a8222ff48820
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR unevictable_pgs_munlocked " (since Linux 2.6.28)"
.\" commit 5344b7e648980cc2ca613ec03a56a8222ff48820
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR unevictable_pgs_cleared " (since Linux 2.6.28)"
.\" commit 5344b7e648980cc2ca613ec03a56a8222ff48820
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.TP
.IR unevictable_pgs_stranded " (since Linux 2.6.28)"
.\" commit 5344b7e648980cc2ca613ec03a56a8222ff48820
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS .
.\" Linux 3.7 removed unevictable_pgs_mlockfreed
.TP
.IR thp_fault_alloc " (since Linux 2.6.39)"
.\" commit 81ab4201fb7d91d6b0cd9ad5b4b16776e4bed145
See the kernel source file
.IR Documentation/admin\-guide/mm/transhuge.rst .
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_TRANSPARENT_HUGEPAGE .
.TP
.IR thp_fault_fallback " (since Linux 2.6.39)"
.\" commit 81ab4201fb7d91d6b0cd9ad5b4b16776e4bed145
See the kernel source file
.IR Documentation/admin\-guide/mm/transhuge.rst .
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_TRANSPARENT_HUGEPAGE .
.TP
.IR thp_collapse_alloc " (since Linux 2.6.39)"
.\" commit 81ab4201fb7d91d6b0cd9ad5b4b16776e4bed145
See the kernel source file
.IR Documentation/admin\-guide/mm/transhuge.rst .
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_TRANSPARENT_HUGEPAGE .
.TP
.IR thp_collapse_alloc_failed " (since Linux 2.6.39)"
.\" commit 81ab4201fb7d91d6b0cd9ad5b4b16776e4bed145
See the kernel source file
.IR Documentation/admin\-guide/mm/transhuge.rst .
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_TRANSPARENT_HUGEPAGE .
.TP
.IR thp_split " (since Linux 2.6.39)"
.\" commit 81ab4201fb7d91d6b0cd9ad5b4b16776e4bed145
See the kernel source file
.IR Documentation/admin\-guide/mm/transhuge.rst .
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_TRANSPARENT_HUGEPAGE .
.TP
.IR thp_zero_page_alloc " (since Linux 3.8)"
.\" commit d8a8e1f0da3d29d7268b3300c96a059d63901b76
See the kernel source file
.IR Documentation/admin\-guide/mm/transhuge.rst .
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_TRANSPARENT_HUGEPAGE .
.TP
.IR thp_zero_page_alloc_failed " (since Linux 3.8)"
.\" commit d8a8e1f0da3d29d7268b3300c96a059d63901b76
See the kernel source file
.IR Documentation/admin\-guide/mm/transhuge.rst .
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_TRANSPARENT_HUGEPAGE .
.TP
.IR balloon_inflate " (since Linux 3.18)"
.\" commit 09316c09dde33aae14f34489d9e3d243ec0d5938
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_MEMORY_BALLOON .
.TP
.IR balloon_deflate " (since Linux 3.18)"
.\" commit 09316c09dde33aae14f34489d9e3d243ec0d5938
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS
.\" and
.\" .BR CONFIG_MEMORY_BALLOON .
.TP
.IR balloon_migrate " (since Linux 3.18)"
.\" commit 09316c09dde33aae14f34489d9e3d243ec0d5938
.\" Present only if the kernel was configured with
.\" .BR CONFIG_VM_EVENT_COUNTERS ,
.\" .BR CONFIG_MEMORY_BALLOON ,
.\" and
.\" .BR CONFIG_BALLOON_COMPACTION .
.TP
.IR nr_tlb_remote_flush " (since Linux 3.12)"
.\" commit 9824cf9753ecbe8f5b47aa9b2f218207defea211
.\" Present only if the kernel was configured with
.\" .BR CONFIG_DEBUG_TLBFLUSH
.\" and
.\" .BR CONFIG_SMP .
.TP
.IR nr_tlb_remote_flush_received " (since Linux 3.12)"
.\" commit 9824cf9753ecbe8f5b47aa9b2f218207defea211
.\" Present only if the kernel was configured with
.\" .BR CONFIG_DEBUG_TLBFLUSH
.\" and
.\" .BR CONFIG_SMP .
.TP
.IR nr_tlb_local_flush_all " (since Linux 3.12)"
.\" commit 9824cf9753ecbe8f5b47aa9b2f218207defea211
.\" Present only if the kernel was configured with
.\" .BR CONFIG_DEBUG_TLBFLUSH .
.TP
.IR nr_tlb_local_flush_one " (since Linux 3.12)"
.\" commit 9824cf9753ecbe8f5b47aa9b2f218207defea211
.\" Present only if the kernel was configured with
.\" .BR CONFIG_DEBUG_TLBFLUSH .
.TP
.IR vmacache_find_calls " (since Linux 3.16)"
.\" commit 4f115147ff802267d0aa41e361c5aa5bd933d896
.\" Present only if the kernel was configured with
.\" .BR CONFIG_DEBUG_VM_VMACACHE .
.TP
.IR vmacache_find_hits " (since Linux 3.16)"
.\" commit 4f115147ff802267d0aa41e361c5aa5bd933d896
.\" Present only if the kernel was configured with
.\" .BR CONFIG_DEBUG_VM_VMACACHE .
.TP
.IR vmacache_full_flushes " (since Linux 3.19)"
.\" commit f5f302e21257ebb0c074bbafc37606c26d28cc3d
.\" Present only if the kernel was configured with
.\" .BR CONFIG_DEBUG_VM_VMACACHE .
.RE
.SH SEE ALSO
.BR proc (5)
