.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_pid_autogroup 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
proc_pid_autogroup \- group tasks for the scheduler
.SH DESCRIPTION
.TP
.IR /proc/ pid /autogroup " (since Linux 2.6.38)"
.\" commit 5091faa449ee0b7d73bc296a93bca9540fc51d0a
See
.BR sched (7).
.SH SEE ALSO
.BR proc (5)
