.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_kallsyms 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/kallsyms \- kernel exported symbols
.SH DESCRIPTION
.TP
.IR /proc/kallsyms " (since Linux 2.5.71)"
This holds the kernel exported symbol definitions used by the
.BR modules (X)
tools to dynamically link and bind loadable modules.
In Linux 2.5.47 and earlier, a similar file with slightly different syntax
was named
.IR ksyms .
.SH HISTORY
.TP
.IR /proc/ksyms " (Linux 1.1.23\[en]2.5.47)"
See
.IR /proc/kallsyms .
.SH SEE ALSO
.BR proc (5)
