.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_pid_mounts 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/pid/mounts \- mounted filesystems
.SH DESCRIPTION
.TP
.IR /proc/ pid /mounts " (since Linux 2.4.19)"
This file lists all the filesystems currently mounted in the
process's mount namespace (see
.BR mount_namespaces (7)).
The format of this file is documented in
.BR fstab (5).
.IP
Since Linux 2.6.15, this file is pollable:
after opening the file for reading, a change in this file
(i.e., a filesystem mount or unmount) causes
.BR select (2)
to mark the file descriptor as having an exceptional condition, and
.BR poll (2)
and
.BR epoll_wait (2)
mark the file as having a priority event
.RB ( POLLPRI ).
(Before Linux 2.6.30,
a change in this file was indicated by the file descriptor
being marked as readable for
.BR select (2),
and being marked as having an error condition for
.BR poll (2)
and
.BR epoll_wait (2).)
.TP
.I /proc/mounts
Before Linux 2.4.19, this file was a list
of all the filesystems currently mounted on the system.
With the introduction of per-process mount namespaces in Linux 2.4.19 (see
.BR mount_namespaces (7)),
this file became a link to
.IR /proc/self/mounts ,
which lists the mounts of the process's own mount namespace.
The format of this file is documented in
.BR fstab (5).
.SH SEE ALSO
.BR proc (5)
