.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_pid_numa_maps 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/pid/numa_maps \- NUMA memory policy and allocation
.SH DESCRIPTION
.TP
.IR /proc/ pid /numa_maps " (since Linux 2.6.14)"
See
.BR numa (7).
.SH SEE ALSO
.BR proc (5)
