.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_pid_projid_map 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/pid/projid_map \- project ID mappings
.SH DESCRIPTION
.TP
.IR /proc/ pid /projid_map " (since Linux 3.7)"
.\"       commit f76d207a66c3a53defea67e7d36c3eb1b7d6d61d
See
.BR user_namespaces (7).
.SH SEE ALSO
.BR proc (5)
