.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_pid_cgroup 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/pid/cgroup \- control group
.SH DESCRIPTION
.TP
.IR /proc/ pid /cgroup " (since Linux 2.6.24)"
See
.BR cgroups (7).
.SH SEE ALSO
.BR proc (5)
