.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_zoneinfo 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/zoneinfo \- memory zones
.SH DESCRIPTION
.TP
.IR /proc/zoneinfo " (since Linux 2.6.13)"
This file displays information about memory zones.
This is useful for analyzing virtual memory behavior.
.\" FIXME more should be said about /proc/zoneinfo
.SH SEE ALSO
.BR proc (5)
