.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) , Andries Brouwer <aeb@cwi.nl>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_sys_user 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/sys/user/ \- limits on the number of namespaces of various types
.SH DESCRIPTION
.TP
.IR /proc/sys/user/ " (since Linux 4.9)"
See
.BR namespaces (7).
.SH SEE ALSO
.BR proc (5),
.BR proc_sys (5)
