.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_uptime 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/uptime \- system uptime
.SH DESCRIPTION
.TP
.I /proc/uptime
This file contains two numbers (values in seconds): the uptime of the
system (including time spent in suspend) and the amount of time spent
in the idle process.
.SH SEE ALSO
.BR proc (5)
