.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_keys 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/keys, /proc/key\-users \- in-kernel key management
.SH DESCRIPTION
.TP
.IR /proc/keys " (since Linux 2.6.10)"
See
.BR keyrings (7).
.TP
.IR /proc/key\-users " (since Linux 2.6.10)"
See
.BR keyrings (7).
.SH SEE ALSO
.BR proc (5)
