.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_iomem 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/iomem \- I/O memory map
.SH DESCRIPTION
.TP
.I /proc/iomem
I/O memory map in Linux 2.4.
.SH SEE ALSO
.BR proc (5)
