.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_pid_uid_map 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/pid/gid_map, /proc/pid/uid_map \- user and group ID mappings
.SH DESCRIPTION
.TP
.IR /proc/ pid /gid_map " (since Linux 3.5)"
See
.BR user_namespaces (7).
.TP
.IR /proc/ pid /uid_map " (since Linux 3.5)"
See
.BR user_namespaces (7).
.SH SEE ALSO
.BR proc (5)
