.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) , Andries Brouwer <aeb@cwi.nl>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_sys_dev 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/sys/dev/ \- device-specific information
.SH DESCRIPTION
.TP
.I /proc/sys/dev/
This directory contains device-specific information (e.g.,
.IR dev/cdrom/info ).
On
some systems, it may be empty.
.SH SEE ALSO
.BR proc (5),
.BR proc_sys (5)
