.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_fs 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/fs/ \- mounted filesystems
.SH DESCRIPTION
.TP
.I /proc/fs/
.\" FIXME Much more needs to be said about /proc/fs
.\"
Contains subdirectories that in turn contain files
with information about (certain) mounted filesystems.
.SH SEE ALSO
.BR proc (5)
