.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_ioports 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/ioports \- I/O port regions
.SH DESCRIPTION
.TP
.I /proc/ioports
This is a list of currently registered Input-Output port regions that
are in use.
.SH SEE ALSO
.BR proc (5)
