.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_version 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/version \- kernel version
.SH DESCRIPTION
.TP
.I /proc/version
This string identifies the kernel version that is currently running.
It includes the contents of
.IR /proc/sys/kernel/ostype ,
.IR /proc/sys/kernel/osrelease ,
and
.IR /proc/sys/kernel/version .
For example:
.IP
.in +4n
.EX
Linux version 1.0.9 (quinlan@phaze) #1 Sat May 14 01:51:54 EDT 1994
.EE
.in
.SH SEE ALSO
.BR proc (5)
