.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_diskstats 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/diskstats \- disk I/O statistics
.SH DESCRIPTION
.TP
.IR /proc/diskstats " (since Linux 2.5.69)"
This file contains disk I/O statistics for each disk device.
See the Linux kernel source file
.I Documentation/admin\-guide/iostats.rst
(or
.I Documentation/iostats.txt
before Linux 5.3)
for further information.
.SH SEE ALSO
.BR proc (5)
