.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_kpagecgroup 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/kpagecgroup \- memory cgroups
.SH DESCRIPTION
.TP
.IR /proc/kpagecgroup " (since Linux 4.3)"
.\" commit 80ae2fdceba8313b0433f899bdd9c6c463291a17
This file contains a 64-bit inode number of
the memory cgroup each page is charged to,
indexed by page frame number (see the discussion of
.IR /proc/ pid /pagemap ).
.IP
The
.I /proc/kpagecgroup
file is present only if the
.B CONFIG_MEMCG
kernel configuration option is enabled.
.SH SEE ALSO
.BR proc (5)
