.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_tid_children 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/tid/children \- child tasks
.SH DESCRIPTION
.TP
.IR /proc/ tid /children " (since Linux 3.5)"
.\" commit 818411616baf46ceba0cff6f05af3a9b294734f7
A space-separated list of child tasks of this task.
Each child task is represented by its TID.
.IP
.\" see comments in get_children_pid() in fs/proc/array.c
This option is intended for use by the checkpoint-restore (CRIU) system,
and reliably provides a list of children only if all of the child processes
are stopped or frozen.
It does not work properly if children of the target task exit while
the file is being read!
Exiting children may cause non-exiting children to be omitted from the list.
This makes this interface even more unreliable than classic PID-based
approaches if the inspected task and its children aren't frozen,
and most code should probably not use this interface.
.IP
Until Linux 4.2, the presence of this file was governed by the
.B CONFIG_CHECKPOINT_RESTORE
kernel configuration option.
Since Linux 4.2,
.\" commit 2e13ba54a2682eea24918b87ad3edf70c2cf085b
it is governed by the
.B CONFIG_PROC_CHILDREN
option.
.SH SEE ALSO
.BR proc (5)
