.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_mtrr 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/mtrr \- memory type range registers
.SH DESCRIPTION
.TP
.I /proc/mtrr
Memory Type Range Registers.
See the Linux kernel source file
.I Documentation/x86/mtrr.rst
(or
.I Documentation/x86/mtrr.txt
.\" commit 7225e75144b9718cbbe1820d9c011c809d5773fd
before Linux 5.2, or
.I Documentation/mtrr.txt
before Linux 2.6.28)
for details.
.SH SEE ALSO
.BR proc (5)
