.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_swaps 5 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
/proc/swaps \- swap areas
.SH DESCRIPTION
.TP
.I /proc/swaps
Swap areas in use.
See also
.BR swapon (8).
.SH SEE ALSO
.BR proc (5)
