.\" Copyright (C) 1994, 1995, Daniel Quinlan <quinlan@yggdrasil.com>
.\" Copyright (C) 2002-2008, 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright (C) , Andries Brouwer <aeb@cwi.nl>
.\" Copyright (C) 2023, Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_sys 5 2024-06-15 "Linux man-pages (unreleased)"
.SH NAME
/proc/sys/ \- system information, and sysctl pseudo-filesystem
.SH DESCRIPTION
.TP
.I /proc/sys/
This directory (present since Linux 1.3.57) contains a number of files
and subdirectories corresponding to kernel variables.
These variables can be read and in some cases modified using
the \fI/proc\fP filesystem, and the (deprecated)
.BR sysctl (2)
system call.
.IP
String values may be terminated by either \[aq]\[rs]0\[aq] or \[aq]\[rs]n\[aq].
.IP
Integer and long values may be written either in decimal or in
hexadecimal notation (e.g., 0x3FFF).
When writing multiple integer or long values, these may be separated
by any of the following whitespace characters:
\[aq]\ \[aq], \[aq]\[rs]t\[aq], or \[aq]\[rs]n\[aq].
Using other separators leads to the error
.BR EINVAL .
.SH SEE ALSO
.BR proc (5)
