# Copyright 2024, Alejandro Colomar <alx@kernel.org>
# SPDX-License-Identifier: LGPL-3.0-only WITH LGPL-3.0-linking-exception


ifndef MAKEFILE_CONFIGURE_BUILD_DEPENDS_FONTFORGE_FONTFORGE_INCLUDED
MAKEFILE_CONFIGURE_BUILD_DEPENDS_FONTFORGE_FONTFORGE_INCLUDED := 1


DEFAULT_FONTFORGEFLAGS :=
EXTRA_FONTFORGEFLAGS   :=
FONTFORGEFLAGS         := $(DEFAULT_FONTFORGEFLAGS) $(EXTRA_FONTFORGEFLAGS)
FONTFORGE              := fontforge


endif  # include guard
