---
abstract: 'A perl module for parsing XML documents'
author:
  - 'Clark Cooper (coopercc@netheaven.com)'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-Parser
no_index:
  directory:
    - t
    - inc
requires:
  LWP::UserAgent: '0'
  perl: '5.004050'
resources:
  bugtracker: https://github.com/toddr/XML-Parser/issues
  repository: http://github.com/toddr/XML-Parser
version: '2.47'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
