'\" t
.\" Copyright (c) 2015, IBM Corporation.
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH __ppc_yield 3 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
__ppc_yield, __ppc_mdoio, __ppc_mdoom \-
Hint the processor to release shared resources
.SH LIBRARY
Standard C library
.RI ( libc ", " \-lc )
.SH SYNOPSIS
.nf
.B #include <sys/platform/ppc.h>
.P
.B void __ppc_yield(void);
.B void __ppc_mdoio(void);
.B void __ppc_mdoom(void);
.fi
.SH DESCRIPTION
These functions
provide hints about the usage of resources that are shared with other
processors on the Power architecture.
They can be used, for example, if a program waiting on a lock intends
to divert the shared resources to be used by other processors.
.P
.BR __ppc_yield ()
provides a hint that performance will probably be improved if shared
resources dedicated to the executing processor are released for use by
other processors.
.P
.BR __ppc_mdoio ()
provides a hint that performance will probably be improved if shared
resources dedicated to the executing processor are released until all
outstanding storage accesses to caching-inhibited storage have been
completed.
.P
.BR __ppc_mdoom ()
provides a hint that performance will probably be improved if shared
resources dedicated to the executing processor are released until all
outstanding storage accesses to cacheable storage for which the data
is not in the cache have been completed.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR __ppc_yield (),
.BR __ppc_mdoio (),
.BR __ppc_mdoom ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
GNU.
.SH HISTORY
glibc 2.18.
.SH SEE ALSO
.BR __ppc_set_ppr_med (3)
.P
.I Power ISA, Book\~II - Section\~3.2 ("or" architecture)
