.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\"
.\" SPDX-License-Identifier: GPL-1.0-or-later
.\"
.TH cexp2 3 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
cexp2, cexp2f, cexp2l \- base-2 exponent of a complex number
.SH LIBRARY
Math library
.RI ( libm ", " \-lm )
.SH SYNOPSIS
.nf
.B #include <complex.h>
.P
.BI "double complex cexp2(double complex " z );
.BI "float complex cexp2f(float complex " z );
.BI "long double complex cexp2l(long double complex " z );
.fi
.SH DESCRIPTION
The function returns 2 raised to the power of
.IR z .
.SH STANDARDS
These function names are reserved for future use in C99.
.P
As at glibc 2.31, these functions are not provided in glibc.
.\" But reserved in NAMESPACE.
.SH SEE ALSO
.BR cabs (3),
.BR cexp (3),
.BR clog10 (3),
.BR complex (7)
