.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\"
.\" SPDX-License-Identifier: GPL-1.0-or-later
.\"
.TH clog2 3 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
clog2, clog2f, clog2l \- base-2 logarithm of a complex number
.SH LIBRARY
Math library
.RI ( libm ", " \-lm )
.SH SYNOPSIS
.nf
.B #include <complex.h>
.P
.BI "double complex clog2(double complex " z );
.BI "float complex clog2f(float complex " z );
.BI "long double complex clog2l(long double complex " z );
.fi
.SH DESCRIPTION
The call
.I clog2(z)
is equivalent to
.IR clog(z)/log(2) .
.P
The other functions perform the same task for
.I float
and
.IR "long double" .
.P
Note that
.I z
close to zero will cause an overflow.
.SH STANDARDS
None.
.SH HISTORY
These function names are reserved for future use in C99.
.P
Not yet in glibc, as at glibc 2.19.
.\" But reserved in NAMESPACE.
.SH SEE ALSO
.BR cabs (3),
.BR cexp (3),
.BR clog (3),
.BR clog10 (3),
.BR complex (7)
