'\" t
.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\"
.\" SPDX-License-Identifier: GPL-1.0-or-later
.\"
.TH csinh 3 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
csinh, csinhf, csinhl \- complex hyperbolic sine
.SH LIBRARY
Math library
.RI ( libm ", " \-lm )
.SH SYNOPSIS
.nf
.B #include <complex.h>
.P
.BI "double complex csinh(double complex " z );
.BI "float complex csinhf(float complex " z );
.BI "long double complex csinhl(long double complex " z );
.fi
.SH DESCRIPTION
These functions calculate the complex hyperbolic sine of
.IR z .
.P
The complex hyperbolic sine function is defined as:
.P
.in +4n
.EX
csinh(z) = (exp(z)\-exp(\-z))/2
.EE
.in
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR csinh (),
.BR csinhf (),
.BR csinhl ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
C11, POSIX.1-2008.
.SH HISTORY
glibc 2.1.
C99, POSIX.1-2001.
.SH SEE ALSO
.BR cabs (3),
.BR casinh (3),
.BR ccosh (3),
.BR ctanh (3),
.BR complex (7)
