'\" t
.\" Copyright (c) 2008 Linux Foundation, written by Michael Kerrisk
.\"     <mtk.manpages@gmail.com>
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH pthread_attr_setinheritsched 3 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
pthread_attr_setinheritsched, pthread_attr_getinheritsched \- set/get
inherit-scheduler attribute in thread attributes object
.SH LIBRARY
POSIX threads library
.RI ( libpthread ", " \-lpthread )
.SH SYNOPSIS
.nf
.B #include <pthread.h>
.P
.BI "int pthread_attr_setinheritsched(pthread_attr_t *" attr ,
.BI "                                 int " inheritsched );
.BI "int pthread_attr_getinheritsched(const pthread_attr_t *restrict " attr ,
.BI "                                 int *restrict " inheritsched );
.fi
.SH DESCRIPTION
The
.BR pthread_attr_setinheritsched ()
function sets the inherit-scheduler attribute of the
thread attributes object referred to by
.I attr
to the value specified in
.IR inheritsched .
The inherit-scheduler attribute determines whether a thread created using
the thread attributes object
.I attr
will inherit its scheduling attributes from the calling thread
or whether it will take them from
.IR attr .
.P
The following scheduling attributes are affected by the
inherit-scheduler attribute:
scheduling policy
.RB ( pthread_attr_setschedpolicy (3)),
scheduling priority
.RB ( pthread_attr_setschedparam (3)),
and contention scope
.RB ( pthread_attr_setscope (3)).
.P
The following values may be specified in
.IR inheritsched :
.TP
.B PTHREAD_INHERIT_SCHED
Threads that are created using
.I attr
inherit scheduling attributes from the creating thread;
the scheduling attributes in
.I attr
are ignored.
.TP
.B PTHREAD_EXPLICIT_SCHED
Threads that are created using
.I attr
take their scheduling attributes from the values specified
by the attributes object.
.\" FIXME Document the defaults for scheduler settings
.P
The default setting of the inherit-scheduler attribute in
a newly initialized thread attributes object is
.BR PTHREAD_INHERIT_SCHED .
.P
The
.BR pthread_attr_getinheritsched ()
returns the inherit-scheduler attribute of the thread attributes object
.I attr
in the buffer pointed to by
.IR inheritsched .
.SH RETURN VALUE
On success, these functions return 0;
on error, they return a nonzero error number.
.SH ERRORS
.BR pthread_attr_setinheritsched ()
can fail with the following error:
.TP
.B EINVAL
Invalid value in
.IR inheritsched .
.P
POSIX.1 also documents an optional
.B ENOTSUP
error ("attempt was made to set the attribute to an unsupported value") for
.BR pthread_attr_setinheritsched ().
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR pthread_attr_setinheritsched (),
.BR pthread_attr_getinheritsched ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
POSIX.1-2008.
.SH HISTORY
glibc 2.0.
POSIX.1-2001.
.SH BUGS
As at glibc 2.8, if a thread attributes object is initialized using
.BR pthread_attr_init (3),
then the scheduling policy of the attributes object is set to
.B SCHED_OTHER
and the scheduling priority is set to 0.
However, if the inherit-scheduler attribute is then set to
.BR PTHREAD_EXPLICIT_SCHED ,
then a thread created using the attribute object
wrongly inherits its scheduling attributes from the creating thread.
This bug does not occur if either the scheduling policy or
scheduling priority attribute is explicitly set
in the thread attributes object before calling
.BR pthread_create (3).
.\" FIXME . Track status of the following bug:
.\" http://sourceware.org/bugzilla/show_bug.cgi?id=7007
.SH EXAMPLES
See
.BR pthread_setschedparam (3).
.SH SEE ALSO
.ad l
.nh
.BR pthread_attr_init (3),
.BR pthread_attr_setschedparam (3),
.BR pthread_attr_setschedpolicy (3),
.BR pthread_attr_setscope (3),
.BR pthread_create (3),
.BR pthread_setschedparam (3),
.BR pthread_setschedprio (3),
.BR pthreads (7),
.BR sched (7)
