'\" t
.\" Copyright (c) 2008 Linux Foundation, written by Michael Kerrisk
.\"     <mtk.manpages@gmail.com>
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH pthread_equal 3 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
pthread_equal \- compare thread IDs
.SH LIBRARY
POSIX threads library
.RI ( libpthread ", " \-lpthread )
.SH SYNOPSIS
.nf
.B #include <pthread.h>
.P
.BI "int pthread_equal(pthread_t " t1 ", pthread_t " t2 );
.fi
.SH DESCRIPTION
The
.BR pthread_equal ()
function compares two thread identifiers.
.SH RETURN VALUE
If the two thread IDs are equal,
.BR pthread_equal ()
returns a nonzero value; otherwise, it returns 0.
.SH ERRORS
This function always succeeds.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR pthread_equal ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
POSIX.1-2008.
.SH HISTORY
POSIX.1-2001.
.SH NOTES
The
.BR pthread_equal ()
function is necessary because thread IDs should be considered opaque:
there is no portable way for applications to directly compare two
.I pthread_t
values.
.SH SEE ALSO
.BR pthread_create (3),
.BR pthread_self (3),
.BR pthreads (7)
