'\" t
.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sun Jul 25 10:40:51 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified Sun Apr 14 16:20:34 1996 by Andries Brouwer (aeb@cwi.nl)
.TH siginterrupt 3 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
siginterrupt \- allow signals to interrupt system calls
.SH LIBRARY
Standard C library
.RI ( libc ", " \-lc )
.SH SYNOPSIS
.nf
.B #include <signal.h>
.P
.BI "[[deprecated]] int siginterrupt(int " sig ", int " flag );
.fi
.P
.RS -4
Feature Test Macro Requirements for glibc (see
.BR feature_test_macros (7)):
.RE
.P
.BR siginterrupt ():
.nf
    _XOPEN_SOURCE >= 500
.\"    || _XOPEN_SOURCE && _XOPEN_SOURCE_EXTENDED
        || /* Since glibc 2.12: */ _POSIX_C_SOURCE >= 200809L
        || /* glibc <= 2.19: */ _BSD_SOURCE
.fi
.SH DESCRIPTION
The
.BR siginterrupt ()
function changes the restart behavior when
a system call is interrupted by the signal \fIsig\fP.
If the \fIflag\fP
argument is false (0), then system calls will be restarted if interrupted
by the specified signal \fIsig\fP.
This is the default behavior in Linux.
.P
If the \fIflag\fP argument is true (1) and no data has been transferred,
then a system call interrupted by the signal \fIsig\fP will return \-1
and \fIerrno\fP will be set to
.BR EINTR .
.P
If the \fIflag\fP argument is true (1) and data transfer has started,
then the system call will be interrupted and will return the actual
amount of data transferred.
.SH RETURN VALUE
The
.BR siginterrupt ()
function returns 0 on success.
It returns \-1 if the
signal number
.I sig
is invalid, with
.I errno
set to indicate the error.
.SH ERRORS
.TP
.B EINVAL
The specified signal number is invalid.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lbx
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR siginterrupt ()
T}	Thread safety	T{
.na
.nh
MT-Unsafe const:sigintr
T}
.TE
.SH STANDARDS
POSIX.1-2008.
.SH HISTORY
4.3BSD, POSIX.1-2001.
Obsolete in POSIX.1-2008,
recommending the use of
.BR sigaction (2)
with the
.B SA_RESTART
flag instead.
.SH SEE ALSO
.BR signal (2)
