'\" t
.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Mon Apr 12 12:51:24 1993, David Metcalfe
.\" 2006-05-19, Justin Pryzby <pryzbyj@justinpryzby.com>
.\"	Document strchrnul(3).
.\"
.TH strchr 3 2024-06-15 "Linux man-pages (unreleased)"
.SH NAME
strchr, strrchr, strchrnul \- locate character in string
.SH LIBRARY
Standard C library
.RI ( libc ", " \-lc )
.SH SYNOPSIS
.nf
.B #include <string.h>
.P
.BI "char *strchr(const char *" s ", int " c );
.BI "char *strrchr(const char *" s ", int " c );
.P
.BR "#define _GNU_SOURCE" "         /* See feature_test_macros(7) */"
.B #include <string.h>
.P
.BI "char *strchrnul(const char *" s ", int " c );
.fi
.SH DESCRIPTION
The
.BR strchr ()
function returns a pointer to the first occurrence
of the character
.I c
in the string
.IR s .
.P
The
.BR strrchr ()
function returns a pointer to the last occurrence
of the character
.I c
in the string
.IR s .
.P
The
.BR strchrnul ()
function is like
.BR strchr ()
except that if
.I c
is not found in
.IR s ,
then it returns a pointer to the null byte
at the end of
.IR s ,
rather than NULL.
.P
Here "character" means "byte"; these functions do not work with
wide or multibyte characters.
.SH RETURN VALUE
The
.BR strchr ()
and
.BR strrchr ()
functions return a pointer to
the matched character or NULL if the character is not found.
The terminating null byte is considered part of the string,
so that if
.I c
is specified as \[aq]\[rs]0\[aq],
these functions return a pointer to the terminator.
.P
The
.BR strchrnul ()
function returns a pointer to the matched character,
or a pointer to the null byte at the end of
.I s
(i.e.,
.IR "s+strlen(s)" )
if the character is not found.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR strchr (),
.BR strrchr (),
.BR strchrnul ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
.TP
.BR strchr ()
.TQ
.BR strrchr ()
C11, POSIX.1-2008.
.TP
.BR strchrnul ()
GNU.
.SH HISTORY
.TP
.BR strchr ()
.TQ
.BR strrchr ()
POSIX.1-2001, C89, SVr4, 4.3BSD.
.TP
.BR strchrnul ()
glibc 2.1.1,
FreeBSD 10,
NetBSD 8.
.SH SEE ALSO
.BR memchr (3),
.BR string (3),
.BR strlen (3),
.BR strpbrk (3),
.BR strsep (3),
.BR strspn (3),
.BR strstr (3),
.BR strtok (3),
.BR wcschr (3),
.BR wcsrchr (3)
