.\" Copyright (C) 2024 Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH TIMEVAL_TO_TIMESPEC 3 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
TIMEVAL_TO_TIMESPEC,
TIMESPEC_TO_TIMEVAL
\-
convert between time structures
.SH SYNOPSIS
.nf
.B #define _GNU_SOURCE
.B #include <sys/time.h>
.P
.BI "void TIMEVAL_TO_TIMESPEC(const struct timeval *" tv ", struct timespec *" ts );
.BI "void TIMESPEC_TO_TIMEVAL(struct timeval *" tv ", const struct timespec *" ts );
.fi
.SH DESCRIPTION
These macros convert from a
.BR timeval (3type)
to a
.BR timespec (3type)
structure,
and vice versa,
respectively.
.P
This is especially useful for writing interfaces that receive a type,
but are implemented with calls to functions that receive the other one.
.SH STANDARDS
GNU,
BSD.
