'\" t
.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.TH wcslen 3 2024-06-15 "Linux man-pages (unreleased)"
.SH NAME
wcslen \- determine the length of a wide-character string
.SH LIBRARY
Standard C library
.RI ( libc ", " \-lc )
.SH SYNOPSIS
.nf
.B #include <wchar.h>
.P
.BI "size_t wcslen(const wchar_t *" s );
.fi
.SH DESCRIPTION
The
.BR wcslen ()
function is the wide-character equivalent
of the
.BR strlen (3)
function.
It determines the length of the wide-character string pointed to
by
.IR s ,
excluding the terminating null wide character (L\[aq]\[rs]0\[aq]).
.SH RETURN VALUE
The
.BR wcslen ()
function returns the
number of wide characters in
.IR s .
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR wcslen ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
C11, POSIX.1-2008.
.SH HISTORY
POSIX.1-2001, C99.
.SH NOTES
In cases where the input buffer may not contain
a terminating null wide character,
.BR wcsnlen (3)
should be used instead.
.SH SEE ALSO
.BR strlen (3)
