'\" t
.TH "SYSTEMD\-SLEEP\&.CONF" "5" "" "systemd 256.4" "systemd-sleep.conf"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-sleep.conf, sleep.conf.d \- Suspend and hibernation configuration file
.SH "SYNOPSIS"
.PP
.RS 4
/etc/systemd/sleep\&.conf
.RE
.RS 4
/run/systemd/sleep\&.conf
.RE
.RS 4
/usr/lib/systemd/sleep\&.conf
.RE
.RS 4
/etc/systemd/sleep\&.conf\&.d/*\&.conf
.RE
.RS 4
/run/systemd/sleep\&.conf\&.d/*\&.conf
.RE
.RS 4
/usr/lib/systemd/sleep\&.conf\&.d/*\&.conf
.RE
.SH "DESCRIPTION"
.PP
\fBsystemd\fR
supports four general power\-saving modes:
.PP
suspend
.RS 4
a low\-power state where execution of the OS is paused, and complete power loss might result in lost data, and which is fast to enter and exit\&. This corresponds to suspend, standby, or freeze states as understood by the kernel\&.
.sp
Added in version 203\&.
.RE
.PP
hibernate
.RS 4
a low\-power state where execution of the OS is paused, and complete power loss does not result in lost data, and which might be slow to enter and exit\&. This corresponds to the hibernation as understood by the kernel\&.
.sp
Added in version 203\&.
.RE
.PP
hybrid\-sleep
.RS 4
a low\-power state where execution of the OS is paused, which might be slow to enter, and on complete power loss does not result in lost data but might be slower to exit in that case\&. This mode is called suspend\-to\-both by the kernel\&.
.sp
Added in version 203\&.
.RE
.PP
suspend\-then\-hibernate
.RS 4
A low power state where the system is initially suspended (the state is stored in RAM)\&. When the battery level is too low (less than 5%) or a certain timespan has passed, whichever happens first, the system is automatically woken up and then hibernated\&. This establishes a balance between speed and safety\&.
.sp
If the system has no battery, it would be hibernated after
\fIHibernateDelaySec=\fR
has passed\&. If not set, then defaults to
"2h"\&.
.sp
If the system has battery and
\fIHibernateDelaySec=\fR
is not set, low\-battery alarms (ACPI _BTP) are tried first for detecting battery percentage and wake up the system for hibernation\&. If not available, or
\fIHibernateDelaySec=\fR
is set, the system would regularly wake up to check the time and detect the battery percentage/discharging rate\&. The rate is used to schedule the next detection\&. If that is also not available,
\fISuspendEstimationSec=\fR
is used as last resort\&.
.sp
Added in version 239\&.
.RE
.PP
Settings in these files determine what strings will be written to
/sys/power/disk
and
/sys/power/state
by
\fBsystemd-sleep\fR(8)
when
\fBsystemd\fR(1)
attempts to suspend or hibernate the machine\&. See
\fBsystemd.syntax\fR(7)
for a general description of the syntax\&.
.SH "CONFIGURATION DIRECTORIES AND PRECEDENCE"
.PP
The default configuration is set during compilation, so configuration is only needed when it is necessary to deviate from those defaults\&. The main configuration file is loaded from one of the listed directories in order of priority, only the first file found is used:
/etc/systemd/,
/run/systemd/,
/usr/local/lib/systemd/
\&\s-2\u[1]\d\s+2,
/usr/lib/systemd/\&. The vendor version of the file contains commented out entries showing the defaults as a guide to the administrator\&. Local overrides can also be created by creating drop\-ins, as described below\&. The main configuration file can also be edited for this purpose (or a copy in
/etc/
if it\*(Aqs shipped under
/usr/), however using drop\-ins for local configuration is recommended over modifications to the main configuration file\&.
.PP
In addition to the main configuration file, drop\-in configuration snippets are read from
/usr/lib/systemd/*\&.conf\&.d/,
/usr/local/lib/systemd/*\&.conf\&.d/, and
/etc/systemd/*\&.conf\&.d/\&. Those drop\-ins have higher precedence and override the main configuration file\&. Files in the
*\&.conf\&.d/
configuration subdirectories are sorted by their filename in lexicographic order, regardless of in which of the subdirectories they reside\&. When multiple files specify the same option, for options which accept just a single value, the entry in the file sorted last takes precedence, and for options which accept a list of values, entries are collected as they occur in the sorted files\&.
.PP
When packages need to customize the configuration, they can install drop\-ins under
/usr/\&. Files in
/etc/
are reserved for the local administrator, who may use this logic to override the configuration files installed by vendor packages\&. Drop\-ins have to be used to override package drop\-ins, since the main configuration file has lower precedence\&. It is recommended to prefix all filenames in those subdirectories with a two\-digit number and a dash, to simplify the ordering\&. This also defines a concept of drop\-in priorities to allow OS vendors to ship drop\-ins within a specific range lower than the range used by users\&. This should lower the risk of package drop\-ins overriding accidentally drop\-ins defined by users\&. It is recommended to use the range 10\-40 for drop\-ins in
/usr/
and the range 60\-90 for drop\-ins in
/etc/
and
/run/, to make sure that local and transient drop\-ins take priority over drop\-ins shipped by the OS vendor\&.
.PP
To disable a configuration file supplied by the vendor, the recommended way is to place a symlink to
/dev/null
in the configuration directory in
/etc/, with the same filename as the vendor configuration file\&.
.SH "OPTIONS"
.PP
The following options can be configured in the [Sleep] section of
/etc/systemd/sleep\&.conf
or a
sleep\&.conf\&.d
file:
.PP
\fIAllowSuspend=\fR, \fIAllowHibernation=\fR, \fIAllowHybridSleep=\fR, \fIAllowSuspendThenHibernate=\fR
.RS 4
By default any power\-saving mode is advertised if possible (i\&.e\&. the kernel supports that mode, the necessary resources are available)\&. Those switches can be used to disable specific modes\&.
.sp
If
\fIAllowHibernation=no\fR
or
\fIAllowSuspend=no\fR
is used, this implies
\fIAllowSuspendThenHibernate=no\fR
and
\fIAllowHybridSleep=no\fR, since those methods use both suspend and hibernation internally\&.
\fIAllowSuspendThenHibernate=yes\fR
and
\fIAllowHybridSleep=yes\fR
can be used to override and enable those specific modes\&.
.sp
Added in version 240\&.
.RE
.PP
\fISuspendState=\fR
.RS 4
The string to be written to
/sys/power/state
by
\fBsystemd-suspend.service\fR(8)\&. More than one value can be specified by separating multiple values with whitespace\&. They will be tried in turn, until one is written without error\&. If none of the writes succeed, the operation will be aborted\&.
.sp
The allowed set of values is determined by the kernel and is shown in the file itself (use
\fBcat /sys/power/state\fR
to display)\&. See
\m[blue]\fBBasic sysfs Interfaces for System Suspend and Hibernation\fR\m[]\&\s-2\u[2]\d\s+2
for more details\&.
.sp
\fBsystemd-suspend-then-hibernate.service\fR(8)
uses this value when suspending\&.
.sp
Added in version 203\&.
.RE
.PP
\fIHibernateMode=\fR
.RS 4
The string to be written to
/sys/power/disk
by
\fBsystemd-hibernate.service\fR(8)\&. More than one value can be specified by separating multiple values with whitespace\&. They will be tried in turn, until one is written without error\&. If none of the writes succeed, the operation will be aborted\&.
.sp
The allowed set of values is determined by the kernel and is shown in the file itself (use
\fBcat /sys/power/disk\fR
to display)\&. See the kernel documentation page
\m[blue]\fBBasic sysfs Interfaces for System Suspend and Hibernation\fR\m[]\&\s-2\u[2]\d\s+2
for more details\&.
.sp
\fBsystemd-suspend-then-hibernate.service\fR(8)
uses the value of
\fIHibernateMode=\fR
when hibernating\&.
.sp
Added in version 203\&.
.RE
.PP
\fIMemorySleepMode=\fR
.RS 4
The string to be written to
/sys/power/mem_sleep
when
\fBSuspendState=mem\fR
or
\fBhybrid\-sleep\fR
is used\&. More than one value can be specified by separating multiple values with whitespace\&. They will be tried in turn, until one is written without error\&. If none of the writes succeed, the operation will be aborted\&. Defaults to empty, i\&.e\&. the kernel default or kernel command line option
\fImem_sleep_default=\fR
is respected\&.
.sp
The allowed set of values is determined by the kernel and is shown in the file itself (use
\fBcat /sys/power/mem_sleep\fR
to display)\&. See the kernel documentation page
\m[blue]\fBBasic sysfs Interfaces for System Suspend and Hibernation\fR\m[]\&\s-2\u[2]\d\s+2
for more details\&.
.sp
Added in version 256\&.
.RE
.PP
\fIHibernateDelaySec=\fR
.RS 4
The amount of time the system spends in suspend mode before the system is automatically put into hibernate mode\&. Only used by
\fBsystemd-suspend-then-hibernate.service\fR(8)\&. Refer to
\fBsuspend\-then\-hibernate\fR
for details on how this option interacts with other options/system battery state\&.
.sp
Added in version 239\&.
.RE
.PP
\fISuspendEstimationSec=\fR
.RS 4
The RTC alarm will wake the system after the specified timespan to measure the system battery capacity level and estimate battery discharging rate\&. Only used by
\fBsystemd-suspend-then-hibernate.service\fR(8)\&. Refer to
\fBsuspend\-then\-hibernate\fR
for details on how this option interacts with other options/system battery state\&.
.sp
Added in version 253\&.
.RE
.SH "EXAMPLE: FREEZE"
.PP
Example: to exploit the
\(lqfreeze\(rq
mode added in Linux 3\&.9, one can use
\fBsystemctl suspend\fR
with
.sp
.if n \{\
.RS 4
.\}
.nf
[Sleep]
SuspendState=freeze
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBsystemd-sleep\fR(8), \fBsystemd-suspend.service\fR(8), \fBsystemd-hibernate.service\fR(8), \fBsystemd-hybrid-sleep.service\fR(8), \fBsystemd-suspend-then-hibernate.service\fR(8), \fBsystemd\fR(1), \fBsystemd.directives\fR(7)
.SH "NOTES"
.IP " 1." 4
💣💥🧨💥💥💣 Please note that those configuration files must be available at all times. If
/usr/local/
is a separate partition, it may not be available during early boot, and must not be used for configuration.
.IP " 2." 4
Basic sysfs Interfaces for System Suspend and Hibernation
.RS 4
\%https://docs.kernel.org/admin-guide/pm/sleep-states.html#basic-sysfs-interfaces-for-system-suspend-and-hibernation
.RE
