'\" t
.TH "SYSTEMD\&.RESOURCE\-CONTROL" "5" "" "systemd 256.4" "systemd.resource-control"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd.resource-control \- Resource control unit settings
.SH "SYNOPSIS"
.PP
\fIslice\fR\&.slice,
\fIscope\fR\&.scope,
\fIservice\fR\&.service,
\fIsocket\fR\&.socket,
\fImount\fR\&.mount,
\fIswap\fR\&.swap
.SH "DESCRIPTION"
.PP
Unit configuration files for services, slices, scopes, sockets, mount points, and swap devices share a subset of configuration options for resource control of spawned processes\&. Internally, this relies on the Linux Control Groups (cgroups) kernel concept for organizing processes in a hierarchical tree of named groups for the purpose of resource management\&.
.PP
This man page lists the configuration options shared by those six unit types\&. See
\fBsystemd.unit\fR(5)
for the common options of all unit configuration files, and
\fBsystemd.slice\fR(5),
\fBsystemd.scope\fR(5),
\fBsystemd.service\fR(5),
\fBsystemd.socket\fR(5),
\fBsystemd.mount\fR(5), and
\fBsystemd.swap\fR(5)
for more information on the specific unit configuration files\&. The resource control configuration options are configured in the [Slice], [Scope], [Service], [Socket], [Mount], or [Swap] sections, depending on the unit type\&.
.PP
In addition, options which control resources available to programs
\fIexecuted\fR
by systemd are listed in
\fBsystemd.exec\fR(5)\&. Those options complement options listed here\&.
.SS "Enabling and disabling controllers"
.PP
Controllers in the cgroup hierarchy are hierarchical, and resource control is realized by distributing resource assignments between siblings in branches of the cgroup hierarchy\&. There is no need to explicitly
\fIenable\fR
a cgroup controller for a unit\&.
\fBsystemd\fR
will instruct the kernel to enable a controller for a given unit when this unit has configuration for a given controller\&. For example, when
\fICPUWeight=\fR
is set, the
\fBcpu\fR
controller will be enabled, and when
\fITasksMax=\fR
are set, the
\fBpids\fR
controller will be enabled\&. In addition, various controllers may be also be enabled explicitly via the
\fIMemoryAccounting=\fR/\fITasksAccounting=\fR/\fIIOAccounting=\fR
settings\&. Because of how the cgroup hierarchy works, controllers will be automatically enabled for all parent units and for any sibling units starting with the lowest level at which a controller is enabled\&. Units for which a controller is enabled may be subject to resource control even if they don\*(Aqt have any explicit configuration\&.
.PP
Setting
\fIDelegate=\fR
enables any delegated controllers for that unit (see below)\&. The delegatee may then enable controllers for its children as appropriate\&. In particular, if the delegatee is
\fBsystemd\fR
(in the
user@\&.service
unit), it will repeat the same logic as the system instance and enable controllers for user units which have resource limits configured, and their siblings and parents and parents\*(Aq siblings\&.
.PP
Controllers may be
\fIdisabled\fR
for parts of the cgroup hierarchy with
\fIDisableControllers=\fR
(see below)\&.
.PP
\fBExample\ \&1.\ \&Enabling and disabling controllers\fR
.sp
.if n \{\
.RS 4
.\}
.nf
                      \-\&.slice
                     /       \e
              /\-\-\-\-\-/         \e\-\-\-\-\-\-\-\-\-\-\-\-\-\-\e
             /                                \e
      system\&.slice                       user\&.slice
        /       \e                          /      \e
       /         \e                        /        \e
      /           \e              user@42\&.service  user@1000\&.service
     /             \e             Delegate=        Delegate=yes
a\&.service       b\&.slice                             /        \e
CPUWeight=20   DisableControllers=cpu              /          \e
                 /  \e                      app\&.slice      session\&.slice
                /    \e                     CPUWeight=100  CPUWeight=100
               /      \e
       b1\&.service   b2\&.service
                    CPUWeight=1000
        
.fi
.if n \{\
.RE
.\}
.PP
In this hierarchy, the
\fBcpu\fR
controller is enabled for all units shown except
b1\&.service
and
b2\&.service\&. Because there is no explicit configuration for
system\&.slice
and
user\&.slice, CPU resources will be split equally between them\&. Similarly, resources are allocated equally between children of
user\&.slice
and between the child slices beneath
user@1000\&.service\&. Assuming that there is no further configuration of resources or delegation below slices
app\&.slice
or
session\&.slice, the
\fBcpu\fR
controller would not be enabled for units in those slices and CPU resources would be further allocated using other mechanisms, e\&.g\&. based on nice levels\&. The manager for user 42 has delegation enabled without any controllers, i\&.e\&. it can manipulate its subtree of the cgroup hierarchy, but without resource control\&.
.PP
In the slice
system\&.slice, CPU resources are split 1:6 for service
a\&.service, and 5:6 for slice
b\&.slice, because slice
b\&.slice
gets the default value of 100 for
cpu\&.weight
when
\fICPUWeight=\fR
is not set\&.
.PP
\fICPUWeight=\fR
setting in service
b2\&.service
is neutralized by
\fIDisableControllers=\fR
in slice
b\&.slice, so the
\fBcpu\fR
controller would not be enabled for services
b1\&.service
and
b2\&.service, and CPU resources would be further allocated using other mechanisms, e\&.g\&. based on nice levels\&.
.SS "Setting resource controls for a group of related units"
.PP
As described in
\fBsystemd.unit\fR(5), the settings listed here may be set through the main file of a unit and drop\-in snippets in
*\&.d/
directories\&. The list of directories searched for drop\-ins includes names formed by repeatedly truncating the unit name after all dashes\&. This is particularly convenient to set resource limits for a group of units with similar names\&.
.PP
For example, every user gets their own slice
user\-\fInnn\fR\&.slice\&. Drop\-ins with local configuration that affect user 1000 may be placed in
/etc/systemd/system/user\-1000\&.slice,
/etc/systemd/system/user\-1000\&.slice\&.d/*\&.conf, but also
/etc/systemd/system/user\-\&.slice\&.d/*\&.conf\&. This last directory applies to all user slices\&.
.SS ""
.PP
See the
\m[blue]\fBNew Control Group Interfaces\fR\m[]\&\s-2\u[1]\d\s+2
for an introduction on how to make use of resource control APIs from programs\&.
.SH "IMPLICIT DEPENDENCIES"
.PP
The following dependencies are implicitly added:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Units with the
\fISlice=\fR
setting set automatically acquire
\fIRequires=\fR
and
\fIAfter=\fR
dependencies on the specified slice unit\&.
.RE
.SH "OPTIONS"
.PP
Units of the types listed above can have settings for resource control configuration:
.SS "CPU Accounting and Control"
.PP
\fICPUAccounting=\fR
.RS 4
Turn on CPU usage accounting for this unit\&. Takes a boolean argument\&. Note that turning on CPU accounting for one unit will also implicitly turn it on for all units contained in the same slice and for all its parent slices and the units contained therein\&. The system default for this setting may be controlled with
\fIDefaultCPUAccounting=\fR
in
\fBsystemd-system.conf\fR(5)\&.
.sp
Under the unified cgroup hierarchy, CPU accounting is available for all units and this setting has no effect\&.
.sp
Added in version 208\&.
.RE
.PP
\fICPUWeight=\fR\fI\fIweight\fR\fR, \fIStartupCPUWeight=\fR\fI\fIweight\fR\fR
.RS 4
These settings control the
\fBcpu\fR
controller in the unified hierarchy\&.
.sp
These options accept an integer value or a the special string "idle":
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If set to an integer value, assign the specified CPU time weight to the processes executed, if the unified control group hierarchy is used on the system\&. These options control the
"cpu\&.weight"
control group attribute\&. The allowed range is 1 to 10000\&. Defaults to unset, but the kernel default is 100\&. For details about this control group attribute, see
\m[blue]\fBControl Groups v2\fR\m[]\&\s-2\u[2]\d\s+2
and
\m[blue]\fBCFS Scheduler\fR\m[]\&\s-2\u[3]\d\s+2\&. The available CPU time is split up among all units within one slice relative to their CPU time weight\&. A higher weight means more CPU time, a lower weight means less\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If set to the special string "idle", mark the cgroup for "idle scheduling", which means that it will get CPU resources only when there are no processes not marked in this way to execute in this cgroup or its siblings\&. This setting corresponds to the
"cpu\&.idle"
cgroup attribute\&.
.sp
Note that this value only has an effect on cgroup\-v2, for cgroup\-v1 it is equivalent to the minimum weight\&.
.RE
.sp
While
\fIStartupCPUWeight=\fR
applies to the startup and shutdown phases of the system,
\fICPUWeight=\fR
applies to normal runtime of the system, and if the former is not set also to the startup and shutdown phases\&. Using
\fIStartupCPUWeight=\fR
allows prioritizing specific services at boot\-up and shutdown differently than during normal runtime\&.
.sp
In addition to the resource allocation performed by the
\fBcpu\fR
controller, the kernel may automatically divide resources based on session\-id grouping, see "The autogroup feature" in
\fBsched\fR(7)\&. The effect of this feature is similar to the
\fBcpu\fR
controller with no explicit configuration, so users should be careful to not mistake one for the other\&.
.sp
Added in version 232\&.
.RE
.PP
\fICPUQuota=\fR
.RS 4
This setting controls the
\fBcpu\fR
controller in the unified hierarchy\&.
.sp
Assign the specified CPU time quota to the processes executed\&. Takes a percentage value, suffixed with "%"\&. The percentage specifies how much CPU time the unit shall get at maximum, relative to the total CPU time available on one CPU\&. Use values > 100% for allotting CPU time on more than one CPU\&. This controls the
"cpu\&.max"
attribute on the unified control group hierarchy and
"cpu\&.cfs_quota_us"
on legacy\&. For details about these control group attributes, see
\m[blue]\fBControl Groups v2\fR\m[]\&\s-2\u[2]\d\s+2
and
\m[blue]\fBCFS Bandwidth Control\fR\m[]\&\s-2\u[4]\d\s+2\&. Setting
\fICPUQuota=\fR
to an empty value unsets the quota\&.
.sp
Example:
\fICPUQuota=20%\fR
ensures that the executed processes will never get more than 20% CPU time on one CPU\&.
.sp
Added in version 213\&.
.RE
.PP
\fICPUQuotaPeriodSec=\fR
.RS 4
This setting controls the
\fBcpu\fR
controller in the unified hierarchy\&.
.sp
Assign the duration over which the CPU time quota specified by
\fICPUQuota=\fR
is measured\&. Takes a time duration value in seconds, with an optional suffix such as "ms" for milliseconds (or "s" for seconds\&.) The default setting is 100ms\&. The period is clamped to the range supported by the kernel, which is [1ms, 1000ms]\&. Additionally, the period is adjusted up so that the quota interval is also at least 1ms\&. Setting
\fICPUQuotaPeriodSec=\fR
to an empty value resets it to the default\&.
.sp
This controls the second field of
"cpu\&.max"
attribute on the unified control group hierarchy and
"cpu\&.cfs_period_us"
on legacy\&. For details about these control group attributes, see
\m[blue]\fBControl Groups v2\fR\m[]\&\s-2\u[2]\d\s+2
and
\m[blue]\fBCFS Scheduler\fR\m[]\&\s-2\u[3]\d\s+2\&.
.sp
Example:
\fICPUQuotaPeriodSec=10ms\fR
to request that the CPU quota is measured in periods of 10ms\&.
.sp
Added in version 242\&.
.RE
.PP
\fIAllowedCPUs=\fR, \fIStartupAllowedCPUs=\fR
.RS 4
This setting controls the
\fBcpuset\fR
controller in the unified hierarchy\&.
.sp
Restrict processes to be executed on specific CPUs\&. Takes a list of CPU indices or ranges separated by either whitespace or commas\&. CPU ranges are specified by the lower and upper CPU indices separated by a dash\&.
.sp
Setting
\fIAllowedCPUs=\fR
or
\fIStartupAllowedCPUs=\fR
doesn\*(Aqt guarantee that all of the CPUs will be used by the processes as it may be limited by parent units\&. The effective configuration is reported as
\fIEffectiveCPUs=\fR\&.
.sp
While
\fIStartupAllowedCPUs=\fR
applies to the startup and shutdown phases of the system,
\fIAllowedCPUs=\fR
applies to normal runtime of the system, and if the former is not set also to the startup and shutdown phases\&. Using
\fIStartupAllowedCPUs=\fR
allows prioritizing specific services at boot\-up and shutdown differently than during normal runtime\&.
.sp
This setting is supported only with the unified control group hierarchy\&.
.sp
Added in version 244\&.
.RE
.SS "Memory Accounting and Control"
.PP
\fIMemoryAccounting=\fR
.RS 4
This setting controls the
\fBmemory\fR
controller in the unified hierarchy\&.
.sp
Turn on process and kernel memory accounting for this unit\&. Takes a boolean argument\&. Note that turning on memory accounting for one unit will also implicitly turn it on for all units contained in the same slice and for all its parent slices and the units contained therein\&. The system default for this setting may be controlled with
\fIDefaultMemoryAccounting=\fR
in
\fBsystemd-system.conf\fR(5)\&.
.sp
Added in version 208\&.
.RE
.PP
\fIMemoryMin=\fR\fI\fIbytes\fR\fR, \fIMemoryLow=\fR\fI\fIbytes\fR\fR, \fIStartupMemoryLow=\fR\fI\fIbytes\fR\fR, \fIDefaultStartupMemoryLow=\fR\fI\fIbytes\fR\fR
.RS 4
These settings control the
\fBmemory\fR
controller in the unified hierarchy\&.
.sp
Specify the memory usage protection of the executed processes in this unit\&. When reclaiming memory, the unit is treated as if it was using less memory resulting in memory to be preferentially reclaimed from unprotected units\&. Using
\fIMemoryLow=\fR
results in a weaker protection where memory may still be reclaimed to avoid invoking the OOM killer in case there is no other reclaimable memory\&.
.sp
For a protection to be effective, it is generally required to set a corresponding allocation on all ancestors, which is then distributed between children (with the exception of the root slice)\&. Any
\fIMemoryMin=\fR
or
\fIMemoryLow=\fR
allocation that is not explicitly distributed to specific children is used to create a shared protection for all children\&. As this is a shared protection, the children will freely compete for the memory\&.
.sp
Takes a memory size in bytes\&. If the value is suffixed with K, M, G or T, the specified memory size is parsed as Kilobytes, Megabytes, Gigabytes, or Terabytes (with the base 1024), respectively\&. Alternatively, a percentage value may be specified, which is taken relative to the installed physical memory on the system\&. If assigned the special value
"infinity", all available memory is protected, which may be useful in order to always inherit all of the protection afforded by ancestors\&. This controls the
"memory\&.min"
or
"memory\&.low"
control group attribute\&. For details about this control group attribute, see
\m[blue]\fBMemory Interface Files\fR\m[]\&\s-2\u[5]\d\s+2\&.
.sp
Units may have their children use a default
"memory\&.min"
or
"memory\&.low"
value by specifying
\fIDefaultMemoryMin=\fR
or
\fIDefaultMemoryLow=\fR, which has the same semantics as
\fIMemoryMin=\fR
and
\fIMemoryLow=\fR, or
\fIDefaultStartupMemoryLow=\fR
which has the same semantics as
\fIStartupMemoryLow=\fR\&. This setting does not affect
"memory\&.min"
or
"memory\&.low"
in the unit itself\&. Using it to set a default child allocation is only useful on kernels older than 5\&.7, which do not support the
"memory_recursiveprot"
cgroup2 mount option\&.
.sp
While
\fIStartupMemoryLow=\fR
applies to the startup and shutdown phases of the system,
\fIMemoryMin=\fR
applies to normal runtime of the system, and if the former is not set also to the startup and shutdown phases\&. Using
\fIStartupMemoryLow=\fR
allows prioritizing specific services at boot\-up and shutdown differently than during normal runtime\&.
.sp
Added in version 240\&.
.RE
.PP
\fIMemoryHigh=\fR\fI\fIbytes\fR\fR, \fIStartupMemoryHigh=\fR\fI\fIbytes\fR\fR
.RS 4
These settings control the
\fBmemory\fR
controller in the unified hierarchy\&.
.sp
Specify the throttling limit on memory usage of the executed processes in this unit\&. Memory usage may go above the limit if unavoidable, but the processes are heavily slowed down and memory is taken away aggressively in such cases\&. This is the main mechanism to control memory usage of a unit\&.
.sp
Takes a memory size in bytes\&. If the value is suffixed with K, M, G or T, the specified memory size is parsed as Kilobytes, Megabytes, Gigabytes, or Terabytes (with the base 1024), respectively\&. Alternatively, a percentage value may be specified, which is taken relative to the installed physical memory on the system\&. If assigned the special value
"infinity", no memory throttling is applied\&. This controls the
"memory\&.high"
control group attribute\&. For details about this control group attribute, see
\m[blue]\fBMemory Interface Files\fR\m[]\&\s-2\u[5]\d\s+2\&. The effective configuration is reported as
\fIEffectiveMemoryHigh=\fR
(see also
\fIEffectiveMemoryMax=\fR)\&.
.sp
While
\fIStartupMemoryHigh=\fR
applies to the startup and shutdown phases of the system,
\fIMemoryHigh=\fR
applies to normal runtime of the system, and if the former is not set also to the startup and shutdown phases\&. Using
\fIStartupMemoryHigh=\fR
allows prioritizing specific services at boot\-up and shutdown differently than during normal runtime\&.
.sp
Added in version 231\&.
.RE
.PP
\fIMemoryMax=\fR\fI\fIbytes\fR\fR, \fIStartupMemoryMax=\fR\fI\fIbytes\fR\fR
.RS 4
These settings control the
\fBmemory\fR
controller in the unified hierarchy\&.
.sp
Specify the absolute limit on memory usage of the executed processes in this unit\&. If memory usage cannot be contained under the limit, out\-of\-memory killer is invoked inside the unit\&. It is recommended to use
\fIMemoryHigh=\fR
as the main control mechanism and use
\fIMemoryMax=\fR
as the last line of defense\&.
.sp
Takes a memory size in bytes\&. If the value is suffixed with K, M, G or T, the specified memory size is parsed as Kilobytes, Megabytes, Gigabytes, or Terabytes (with the base 1024), respectively\&. Alternatively, a percentage value may be specified, which is taken relative to the installed physical memory on the system\&. If assigned the special value
"infinity", no memory limit is applied\&. This controls the
"memory\&.max"
control group attribute\&. For details about this control group attribute, see
\m[blue]\fBMemory Interface Files\fR\m[]\&\s-2\u[5]\d\s+2\&. The effective configuration is reported as
\fIEffectiveMemoryMax=\fR
(the value is the most stringent limit of the unit and parent slices and it is capped by physical memory)\&.
.sp
While
\fIStartupMemoryMax=\fR
applies to the startup and shutdown phases of the system,
\fIMemoryMax=\fR
applies to normal runtime of the system, and if the former is not set also to the startup and shutdown phases\&. Using
\fIStartupMemoryMax=\fR
allows prioritizing specific services at boot\-up and shutdown differently than during normal runtime\&.
.sp
Added in version 231\&.
.RE
.PP
\fIMemorySwapMax=\fR\fI\fIbytes\fR\fR, \fIStartupMemorySwapMax=\fR\fI\fIbytes\fR\fR
.RS 4
These settings control the
\fBmemory\fR
controller in the unified hierarchy\&.
.sp
Specify the absolute limit on swap usage of the executed processes in this unit\&.
.sp
Takes a swap size in bytes\&. If the value is suffixed with K, M, G or T, the specified swap size is parsed as Kilobytes, Megabytes, Gigabytes, or Terabytes (with the base 1024), respectively\&. Alternatively, a percentage value may be specified, which is taken relative to the specified swap size on the system\&. If assigned the special value
"infinity", no swap limit is applied\&. These settings control the
"memory\&.swap\&.max"
control group attribute\&. For details about this control group attribute, see
\m[blue]\fBMemory Interface Files\fR\m[]\&\s-2\u[5]\d\s+2\&.
.sp
While
\fIStartupMemorySwapMax=\fR
applies to the startup and shutdown phases of the system,
\fIMemorySwapMax=\fR
applies to normal runtime of the system, and if the former is not set also to the startup and shutdown phases\&. Using
\fIStartupMemorySwapMax=\fR
allows prioritizing specific services at boot\-up and shutdown differently than during normal runtime\&.
.sp
Added in version 232\&.
.RE
.PP
\fIMemoryZSwapMax=\fR\fI\fIbytes\fR\fR, \fIStartupMemoryZSwapMax=\fR\fI\fIbytes\fR\fR
.RS 4
These settings control the
\fBmemory\fR
controller in the unified hierarchy\&.
.sp
Specify the absolute limit on zswap usage of the processes in this unit\&. Zswap is a lightweight compressed cache for swap pages\&. It takes pages that are in the process of being swapped out and attempts to compress them into a dynamically allocated RAM\-based memory pool\&. If the limit specified is hit, no entries from this unit will be stored in the pool until existing entries are faulted back or written out to disk\&. See the kernel\*(Aqs
\m[blue]\fBZswap\fR\m[]\&\s-2\u[6]\d\s+2
documentation for more details\&.
.sp
Takes a size in bytes\&. If the value is suffixed with K, M, G or T, the specified size is parsed as Kilobytes, Megabytes, Gigabytes, or Terabytes (with the base 1024), respectively\&. If assigned the special value
"infinity", no limit is applied\&. These settings control the
"memory\&.zswap\&.max"
control group attribute\&. For details about this control group attribute, see
\m[blue]\fBMemory Interface Files\fR\m[]\&\s-2\u[5]\d\s+2\&.
.sp
While
\fIStartupMemoryZSwapMax=\fR
applies to the startup and shutdown phases of the system,
\fIMemoryZSwapMax=\fR
applies to normal runtime of the system, and if the former is not set also to the startup and shutdown phases\&. Using
\fIStartupMemoryZSwapMax=\fR
allows prioritizing specific services at boot\-up and shutdown differently than during normal runtime\&.
.sp
Added in version 253\&.
.RE
.PP
\fIMemoryZSwapWriteback=\fR
.RS 4
This setting controls the
\fBmemory\fR
controller in the unified hierarchy\&.
.sp
Takes a boolean argument\&. When true, pages stored in the Zswap cache are permitted to be written to the backing storage, false otherwise\&. Defaults to true\&. This allows disabling writeback of swap pages for IO\-intensive applications, while retaining the ability to store compressed pages in Zswap\&. See the kernel\*(Aqs
\m[blue]\fBZswap\fR\m[]\&\s-2\u[6]\d\s+2
documentation for more details\&.
.sp
Added in version 256\&.
.RE
.PP
\fIAllowedMemoryNodes=\fR, \fIStartupAllowedMemoryNodes=\fR
.RS 4
These settings control the
\fBcpuset\fR
controller in the unified hierarchy\&.
.sp
Restrict processes to be executed on specific memory NUMA nodes\&. Takes a list of memory NUMA nodes indices or ranges separated by either whitespace or commas\&. Memory NUMA nodes ranges are specified by the lower and upper NUMA nodes indices separated by a dash\&.
.sp
Setting
\fIAllowedMemoryNodes=\fR
or
\fIStartupAllowedMemoryNodes=\fR
doesn\*(Aqt guarantee that all of the memory NUMA nodes will be used by the processes as it may be limited by parent units\&. The effective configuration is reported as
\fIEffectiveMemoryNodes=\fR\&.
.sp
While
\fIStartupAllowedMemoryNodes=\fR
applies to the startup and shutdown phases of the system,
\fIAllowedMemoryNodes=\fR
applies to normal runtime of the system, and if the former is not set also to the startup and shutdown phases\&. Using
\fIStartupAllowedMemoryNodes=\fR
allows prioritizing specific services at boot\-up and shutdown differently than during normal runtime\&.
.sp
This setting is supported only with the unified control group hierarchy\&.
.sp
Added in version 244\&.
.RE
.SS "Process Accounting and Control"
.PP
\fITasksAccounting=\fR
.RS 4
This setting controls the
\fBpids\fR
controller in the unified hierarchy\&.
.sp
Turn on task accounting for this unit\&. Takes a boolean argument\&. If enabled, the kernel will keep track of the total number of tasks in the unit and its children\&. This number includes both kernel threads and userspace processes, with each thread counted individually\&. Note that turning on tasks accounting for one unit will also implicitly turn it on for all units contained in the same slice and for all its parent slices and the units contained therein\&. The system default for this setting may be controlled with
\fIDefaultTasksAccounting=\fR
in
\fBsystemd-system.conf\fR(5)\&.
.sp
Added in version 227\&.
.RE
.PP
\fITasksMax=\fR\fI\fIN\fR\fR
.RS 4
This setting controls the
\fBpids\fR
controller in the unified hierarchy\&.
.sp
Specify the maximum number of tasks that may be created in the unit\&. This ensures that the number of tasks accounted for the unit (see above) stays below a specific limit\&. This either takes an absolute number of tasks or a percentage value that is taken relative to the configured maximum number of tasks on the system\&. If assigned the special value
"infinity", no tasks limit is applied\&. This controls the
"pids\&.max"
control group attribute\&. For details about this control group attribute, the
\m[blue]\fBpids controller\fR\m[]\&\s-2\u[7]\d\s+2\&. The effective configuration is reported as
\fIEffectiveTasksMax=\fR\&.
.sp
The system default for this setting may be controlled with
\fIDefaultTasksMax=\fR
in
\fBsystemd-system.conf\fR(5)\&.
.sp
Added in version 227\&.
.RE
.SS "IO Accounting and Control"
.PP
\fIIOAccounting=\fR
.RS 4
This setting controls the
\fBio\fR
controller in the unified hierarchy\&.
.sp
Turn on Block I/O accounting for this unit, if the unified control group hierarchy is used on the system\&. Takes a boolean argument\&. Note that turning on block I/O accounting for one unit will also implicitly turn it on for all units contained in the same slice and all for its parent slices and the units contained therein\&. The system default for this setting may be controlled with
\fIDefaultIOAccounting=\fR
in
\fBsystemd-system.conf\fR(5)\&.
.sp
Added in version 230\&.
.RE
.PP
\fIIOWeight=\fR\fI\fIweight\fR\fR, \fIStartupIOWeight=\fR\fI\fIweight\fR\fR
.RS 4
These settings control the
\fBio\fR
controller in the unified hierarchy\&.
.sp
Set the default overall block I/O weight for the executed processes, if the unified control group hierarchy is used on the system\&. Takes a single weight value (between 1 and 10000) to set the default block I/O weight\&. This controls the
"io\&.weight"
control group attribute, which defaults to 100\&. For details about this control group attribute, see
\m[blue]\fBIO Interface Files\fR\m[]\&\s-2\u[8]\d\s+2\&. The available I/O bandwidth is split up among all units within one slice relative to their block I/O weight\&. A higher weight means more I/O bandwidth, a lower weight means less\&.
.sp
While
\fIStartupIOWeight=\fR
applies to the startup and shutdown phases of the system,
\fIIOWeight=\fR
applies to the later runtime of the system, and if the former is not set also to the startup and shutdown phases\&. This allows prioritizing specific services at boot\-up and shutdown differently than during runtime\&.
.sp
Added in version 230\&.
.RE
.PP
\fIIODeviceWeight=\fR\fI\fIdevice\fR\fR\fI \fR\fI\fIweight\fR\fR
.RS 4
This setting controls the
\fBio\fR
controller in the unified hierarchy\&.
.sp
Set the per\-device overall block I/O weight for the executed processes, if the unified control group hierarchy is used on the system\&. Takes a space\-separated pair of a file path and a weight value to specify the device specific weight value, between 1 and 10000\&. (Example:
"/dev/sda 1000")\&. The file path may be specified as path to a block device node or as any other file, in which case the backing block device of the file system of the file is determined\&. This controls the
"io\&.weight"
control group attribute, which defaults to 100\&. Use this option multiple times to set weights for multiple devices\&. For details about this control group attribute, see
\m[blue]\fBIO Interface Files\fR\m[]\&\s-2\u[8]\d\s+2\&.
.sp
The specified device node should reference a block device that has an I/O scheduler associated, i\&.e\&. should not refer to partition or loopback block devices, but to the originating, physical device\&. When a path to a regular file or directory is specified it is attempted to discover the correct originating device backing the file system of the specified path\&. This works correctly only for simpler cases, where the file system is directly placed on a partition or physical block device, or where simple 1:1 encryption using dm\-crypt/LUKS is used\&. This discovery does not cover complex storage and in particular RAID and volume management storage devices\&.
.sp
Added in version 230\&.
.RE
.PP
\fIIOReadBandwidthMax=\fR\fI\fIdevice\fR\fR\fI \fR\fI\fIbytes\fR\fR, \fIIOWriteBandwidthMax=\fR\fI\fIdevice\fR\fR\fI \fR\fI\fIbytes\fR\fR
.RS 4
These settings control the
\fBio\fR
controller in the unified hierarchy\&.
.sp
Set the per\-device overall block I/O bandwidth maximum limit for the executed processes, if the unified control group hierarchy is used on the system\&. This limit is not work\-conserving and the executed processes are not allowed to use more even if the device has idle capacity\&. Takes a space\-separated pair of a file path and a bandwidth value (in bytes per second) to specify the device specific bandwidth\&. The file path may be a path to a block device node, or as any other file in which case the backing block device of the file system of the file is used\&. If the bandwidth is suffixed with K, M, G, or T, the specified bandwidth is parsed as Kilobytes, Megabytes, Gigabytes, or Terabytes, respectively, to the base of 1000\&. (Example: "/dev/disk/by\-path/pci\-0000:00:1f\&.2\-scsi\-0:0:0:0 5M")\&. This controls the
"io\&.max"
control group attributes\&. Use this option multiple times to set bandwidth limits for multiple devices\&. For details about this control group attribute, see
\m[blue]\fBIO Interface Files\fR\m[]\&\s-2\u[8]\d\s+2\&.
.sp
Similar restrictions on block device discovery as for
\fIIODeviceWeight=\fR
apply, see above\&.
.sp
Added in version 230\&.
.RE
.PP
\fIIOReadIOPSMax=\fR\fI\fIdevice\fR\fR\fI \fR\fI\fIIOPS\fR\fR, \fIIOWriteIOPSMax=\fR\fI\fIdevice\fR\fR\fI \fR\fI\fIIOPS\fR\fR
.RS 4
These settings control the
\fBio\fR
controller in the unified hierarchy\&.
.sp
Set the per\-device overall block I/O IOs\-Per\-Second maximum limit for the executed processes, if the unified control group hierarchy is used on the system\&. This limit is not work\-conserving and the executed processes are not allowed to use more even if the device has idle capacity\&. Takes a space\-separated pair of a file path and an IOPS value to specify the device specific IOPS\&. The file path may be a path to a block device node, or as any other file in which case the backing block device of the file system of the file is used\&. If the IOPS is suffixed with K, M, G, or T, the specified IOPS is parsed as KiloIOPS, MegaIOPS, GigaIOPS, or TeraIOPS, respectively, to the base of 1000\&. (Example: "/dev/disk/by\-path/pci\-0000:00:1f\&.2\-scsi\-0:0:0:0 1K")\&. This controls the
"io\&.max"
control group attributes\&. Use this option multiple times to set IOPS limits for multiple devices\&. For details about this control group attribute, see
\m[blue]\fBIO Interface Files\fR\m[]\&\s-2\u[8]\d\s+2\&.
.sp
Similar restrictions on block device discovery as for
\fIIODeviceWeight=\fR
apply, see above\&.
.sp
Added in version 230\&.
.RE
.PP
\fIIODeviceLatencyTargetSec=\fR\fI\fIdevice\fR\fR\fI \fR\fI\fItarget\fR\fR
.RS 4
This setting controls the
\fBio\fR
controller in the unified hierarchy\&.
.sp
Set the per\-device average target I/O latency for the executed processes, if the unified control group hierarchy is used on the system\&. Takes a file path and a timespan separated by a space to specify the device specific latency target\&. (Example: "/dev/sda 25ms")\&. The file path may be specified as path to a block device node or as any other file, in which case the backing block device of the file system of the file is determined\&. This controls the
"io\&.latency"
control group attribute\&. Use this option multiple times to set latency target for multiple devices\&. For details about this control group attribute, see
\m[blue]\fBIO Interface Files\fR\m[]\&\s-2\u[8]\d\s+2\&.
.sp
Implies
"IOAccounting=yes"\&.
.sp
These settings are supported only if the unified control group hierarchy is used\&.
.sp
Similar restrictions on block device discovery as for
\fIIODeviceWeight=\fR
apply, see above\&.
.sp
Added in version 240\&.
.RE
.SS "Network Accounting and Control"
.PP
\fIIPAccounting=\fR
.RS 4
Takes a boolean argument\&. If true, turns on IPv4 and IPv6 network traffic accounting for packets sent or received by the unit\&. When this option is turned on, all IPv4 and IPv6 sockets created by any process of the unit are accounted for\&.
.sp
When this option is used in socket units, it applies to all IPv4 and IPv6 sockets associated with it (including both listening and connection sockets where this applies)\&. Note that for socket\-activated services, this configuration setting and the accounting data of the service unit and the socket unit are kept separate, and displayed separately\&. No propagation of the setting and the collected statistics is done, in either direction\&. Moreover, any traffic sent or received on any of the socket unit\*(Aqs sockets is accounted to the socket unit \(em and never to the service unit it might have activated, even if the socket is used by it\&.
.sp
The system default for this setting may be controlled with
\fIDefaultIPAccounting=\fR
in
\fBsystemd-system.conf\fR(5)\&.
.sp
Note that this functionality is currently only available for system services, not for per\-user services\&.
.sp
Added in version 235\&.
.RE
.PP
\fIIPAddressAllow=\fR\fI\fIADDRESS[/PREFIXLENGTH]\&...\fR\fR, \fIIPAddressDeny=\fR\fI\fIADDRESS[/PREFIXLENGTH]\&...\fR\fR
.RS 4
Turn on network traffic filtering for IP packets sent and received over
\fBAF_INET\fR
and
\fBAF_INET6\fR
sockets\&. Both directives take a space separated list of IPv4 or IPv6 addresses, each optionally suffixed with an address prefix length in bits after a
"/"
character\&. If the suffix is omitted, the address is considered a host address, i\&.e\&. the filter covers the whole address (32 bits for IPv4, 128 bits for IPv6)\&.
.sp
The access lists configured with this option are applied to all sockets created by processes of this unit (or in the case of socket units, associated with it)\&. The lists are implicitly combined with any lists configured for any of the parent slice units this unit might be a member of\&. By default both access lists are empty\&. Both ingress and egress traffic is filtered by these settings\&. In case of ingress traffic the source IP address is checked against these access lists, in case of egress traffic the destination IP address is checked\&. The following rules are applied in turn:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Access is granted when the checked IP address matches an entry in the
\fIIPAddressAllow=\fR
list\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Otherwise, access is denied when the checked IP address matches an entry in the
\fIIPAddressDeny=\fR
list\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Otherwise, access is granted\&.
.RE
.sp
In order to implement an allow\-listing IP firewall, it is recommended to use a
\fIIPAddressDeny=\fR\fBany\fR
setting on an upper\-level slice unit (such as the root slice
\-\&.slice
or the slice containing all system services
system\&.slice
\(en see
\fBsystemd.special\fR(7)
for details on these slice units), plus individual per\-service
\fIIPAddressAllow=\fR
lines permitting network access to relevant services, and only them\&.
.sp
Note that for socket\-activated services, the IP access list configured on the socket unit applies to all sockets associated with it directly, but not to any sockets created by the ultimately activated services for it\&. Conversely, the IP access list configured for the service is not applied to any sockets passed into the service via socket activation\&. Thus, it is usually a good idea to replicate the IP access lists on both the socket and the service unit\&. Nevertheless, it may make sense to maintain one list more open and the other one more restricted, depending on the use case\&.
.sp
If these settings are used multiple times in the same unit the specified lists are combined\&. If an empty string is assigned to these settings the specific access list is reset and all previous settings undone\&.
.sp
In place of explicit IPv4 or IPv6 address and prefix length specifications a small set of symbolic names may be used\&. The following names are defined:
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&1.\ \&Special address/network names
.TS
allbox tab(:);
lB lB lB.
T{
Symbolic Name
T}:T{
Definition
T}:T{
Meaning
T}
.T&
l l l
l l l
l l l
l l l.
T{
\fBany\fR
T}:T{
0\&.0\&.0\&.0/0 ::/0
T}:T{
Any host
T}
T{
\fBlocalhost\fR
T}:T{
127\&.0\&.0\&.0/8 ::1/128
T}:T{
All addresses on the local loopback
T}
T{
\fBlink\-local\fR
T}:T{
169\&.254\&.0\&.0/16 fe80::/64
T}:T{
All link\-local IP addresses
T}
T{
\fBmulticast\fR
T}:T{
224\&.0\&.0\&.0/4 ff00::/8
T}:T{
All IP multicasting addresses
T}
.TE
.sp 1
Note that these settings might not be supported on some systems (for example if eBPF control group support is not enabled in the underlying kernel or container manager)\&. These settings will have no effect in that case\&. If compatibility with such systems is desired it is hence recommended to not exclusively rely on them for IP security\&.
.sp
This option cannot be bypassed by prefixing
"+"
to the executable path in the service unit, as it applies to the whole control group\&.
.sp
Added in version 235\&.
.RE
.PP
\fISocketBindAllow=\fR\fI\fIbind\-rule\fR\fR, \fISocketBindDeny=\fR\fI\fIbind\-rule\fR\fR
.RS 4
Configures restrictions on the ability of unit processes to invoke
\fBbind\fR(2)
on a socket\&. Both allow and deny rules may defined that restrict which addresses a socket may be bound to\&.
.sp
\fIbind\-rule\fR
describes socket properties such as
\fIaddress\-family\fR,
\fItransport\-protocol\fR
and
\fIip\-ports\fR\&.
.sp
\fIbind\-rule\fR
:= { [\fIaddress\-family\fR\fB:\fR][\fItransport\-protocol\fR\fB:\fR][\fIip\-ports\fR] |
\fBany\fR
}
.sp
\fIaddress\-family\fR
:= {
\fBipv4\fR
|
\fBipv6\fR
}
.sp
\fItransport\-protocol\fR
:= {
\fBtcp\fR
|
\fBudp\fR
}
.sp
\fIip\-ports\fR
:= {
\fIip\-port\fR
|
\fIip\-port\-range\fR
}
.sp
An optional
\fIaddress\-family\fR
expects
\fBipv4\fR
or
\fBipv6\fR
values\&. If not specified, a rule will be matched for both IPv4 and IPv6 addresses and applied depending on other socket fields, e\&.g\&.
\fItransport\-protocol\fR,
\fIip\-port\fR\&.
.sp
An optional
\fItransport\-protocol\fR
expects
\fBtcp\fR
or
\fBudp\fR
transport protocol names\&. If not specified, a rule will be matched for any transport protocol\&.
.sp
An optional
\fIip\-port\fR
value must lie within 1\&...65535 interval inclusively, i\&.e\&. dynamic port
\fB0\fR
is not allowed\&. A range of sequential ports is described by
\fIip\-port\-range\fR
:=
\fIip\-port\-low\fR\fB\-\fR\fIip\-port\-high\fR, where
\fIip\-port\-low\fR
is smaller than or equal to
\fIip\-port\-high\fR
and both are within 1\&...65535 inclusively\&.
.sp
A special value
\fBany\fR
can be used to apply a rule to any address family, transport protocol and any port with a positive value\&.
.sp
To allow multiple rules assign
\fISocketBindAllow=\fR
or
\fISocketBindDeny=\fR
multiple times\&. To clear the existing assignments pass an empty
\fISocketBindAllow=\fR
or
\fISocketBindDeny=\fR
assignment\&.
.sp
For each of
\fISocketBindAllow=\fR
and
\fISocketBindDeny=\fR, maximum allowed number of assignments is
\fB128\fR\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Binding to a socket is allowed when a socket address matches an entry in the
\fISocketBindAllow=\fR
list\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Otherwise, binding is denied when the socket address matches an entry in the
\fISocketBindDeny=\fR
list\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Otherwise, binding is allowed\&.
.RE
.sp
The feature is implemented with
\fBcgroup/bind4\fR
and
\fBcgroup/bind6\fR
cgroup\-bpf hooks\&.
.sp
Note that these settings apply to any
\fBbind\fR(2)
system call invocation by the unit processes, regardless in which network namespace they are placed\&. Or in other words: changing the network namespace is not a suitable mechanism for escaping these restrictions on
\fBbind()\fR\&.
.sp
Examples:
.sp
.if n \{\
.RS 4
.\}
.nf
\&...
# Allow binding IPv6 socket addresses with a port greater than or equal to 10000\&.
[Service]
SocketBindAllow=ipv6:10000\-65535
SocketBindDeny=any
\&...
# Allow binding IPv4 and IPv6 socket addresses with 1234 and 4321 ports\&.
[Service]
SocketBindAllow=1234
SocketBindAllow=4321
SocketBindDeny=any
\&...
# Deny binding IPv6 socket addresses\&.
[Service]
SocketBindDeny=ipv6
\&...
# Deny binding IPv4 and IPv6 socket addresses\&.
[Service]
SocketBindDeny=any
\&...
# Allow binding only over TCP
[Service]
SocketBindAllow=tcp
SocketBindDeny=any
\&...
# Allow binding only over IPv6/TCP
[Service]
SocketBindAllow=ipv6:tcp
SocketBindDeny=any
\&...
# Allow binding ports within 10000\-65535 range over IPv4/UDP\&.
[Service]
SocketBindAllow=ipv4:udp:10000\-65535
SocketBindDeny=any
\&...
.fi
.if n \{\
.RE
.\}
.sp
This option cannot be bypassed by prefixing
"+"
to the executable path in the service unit, as it applies to the whole control group\&.
.sp
Added in version 249\&.
.RE
.PP
\fIRestrictNetworkInterfaces=\fR
.RS 4
Takes a list of space\-separated network interface names\&. This option restricts the network interfaces that processes of this unit can use\&. By default processes can only use the network interfaces listed (allow\-list)\&. If the first character of the rule is
"~", the effect is inverted: the processes can only use network interfaces not listed (deny\-list)\&.
.sp
This option can appear multiple times, in which case the network interface names are merged\&. If the empty string is assigned the set is reset, all prior assignments will have not effect\&.
.sp
If you specify both types of this option (i\&.e\&. allow\-listing and deny\-listing), the first encountered will take precedence and will dictate the default action (allow vs deny)\&. Then the next occurrences of this option will add or delete the listed network interface names from the set, depending of its type and the default action\&.
.sp
The loopback interface ("lo") is not treated in any special way, you have to configure it explicitly in the unit file\&.
.sp
Example 1: allow\-list
.sp
.if n \{\
.RS 4
.\}
.nf
RestrictNetworkInterfaces=eth1
RestrictNetworkInterfaces=eth2
.fi
.if n \{\
.RE
.\}
.sp
Programs in the unit will be only able to use the eth1 and eth2 network interfaces\&.
.sp
Example 2: deny\-list
.sp
.if n \{\
.RS 4
.\}
.nf
RestrictNetworkInterfaces=~eth1 eth2
.fi
.if n \{\
.RE
.\}
.sp
Programs in the unit will be able to use any network interface but eth1 and eth2\&.
.sp
Example 3: mixed
.sp
.if n \{\
.RS 4
.\}
.nf
RestrictNetworkInterfaces=eth1 eth2
RestrictNetworkInterfaces=~eth1
.fi
.if n \{\
.RE
.\}
.sp
Programs in the unit will be only able to use the eth2 network interface\&.
.sp
This option cannot be bypassed by prefixing
"+"
to the executable path in the service unit, as it applies to the whole control group\&.
.sp
Added in version 250\&.
.RE
.PP
\fINFTSet=\fR\fIfamily\fR:\fItable\fR:\fIset\fR
.RS 4
This setting provides a method for integrating dynamic cgroup, user and group IDs into firewall rules with
\m[blue]\fBNFT\fR\m[]\&\s-2\u[9]\d\s+2
sets\&. The benefit of using this setting is to be able to use the IDs as selectors in firewall rules easily and this in turn allows more fine grained filtering\&. NFT rules for cgroup matching use numeric cgroup IDs, which change every time a service is restarted, making them hard to use in systemd environment otherwise\&. Dynamic and random IDs used by
\fIDynamicUser=\fR
can be also integrated with this setting\&.
.sp
This option expects a whitespace separated list of NFT set definitions\&. Each definition consists of a colon\-separated tuple of source type (one of
"cgroup",
"user"
or
"group"), NFT address family (one of
"arp",
"bridge",
"inet",
"ip",
"ip6", or
"netdev"), table name and set name\&. The names of tables and sets must conform to lexical restrictions of NFT table names\&. The type of the element used in the NFT filter must match the type implied by the directive ("cgroup",
"user"
or
"group") as shown in the table below\&. When a control group or a unit is realized, the corresponding ID will be appended to the NFT sets and it will be be removed when the control group or unit is removed\&.
\fBsystemd\fR
only inserts elements to (or removes from) the sets, so the related NFT rules, tables and sets must be prepared elsewhere in advance\&. Failures to manage the sets will be ignored\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&2.\ \&Defined \fIsource type\fR values
.TS
allbox tab(:);
lB lB lB.
T{
Source type
T}:T{
Description
T}:T{
Corresponding NFT type name
T}
.T&
l l l
l l l
l l l.
T{
"cgroup"
T}:T{
control group ID
T}:T{
"cgroupsv2"
T}
T{
"user"
T}:T{
user ID
T}:T{
"meta skuid"
T}
T{
"group"
T}:T{
group ID
T}:T{
"meta skgid"
T}
.TE
.sp 1
If the firewall rules are reinstalled so that the contents of NFT sets are destroyed, command
\fBsystemctl daemon\-reload\fR
can be used to refill the sets\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
[Unit]
NFTSet=cgroup:inet:filter:my_service user:inet:filter:serviceuser
.fi
.if n \{\
.RE
.\}
.sp
Corresponding NFT rules:
.sp
.if n \{\
.RS 4
.\}
.nf
table inet filter {
        set my_service {
                type cgroupsv2
        }
        set serviceuser {
                typeof meta skuid
        }
        chain x {
                socket cgroupv2 level 2 @my_service accept
                drop
        }
        chain y {
                meta skuid @serviceuser accept
                drop
        }
}
.fi
.if n \{\
.RE
.\}
.sp
This option is only available for system services and is not supported for services running in per\-user instances of the service manager\&.
.sp
Added in version 255\&.
.RE
.SS "BPF Programs"
.PP
\fIIPIngressFilterPath=\fR\fI\fIBPF_FS_PROGRAM_PATH\fR\fR, \fIIPEgressFilterPath=\fR\fI\fIBPF_FS_PROGRAM_PATH\fR\fR
.RS 4
Add custom network traffic filters implemented as BPF programs, applying to all IP packets sent and received over
\fBAF_INET\fR
and
\fBAF_INET6\fR
sockets\&. Takes an absolute path to a pinned BPF program in the BPF virtual filesystem (/sys/fs/bpf/)\&.
.sp
The filters configured with this option are applied to all sockets created by processes of this unit (or in the case of socket units, associated with it)\&. The filters are loaded in addition to filters any of the parent slice units this unit might be a member of as well as any
\fIIPAddressAllow=\fR
and
\fIIPAddressDeny=\fR
filters in any of these units\&. By default there are no filters specified\&.
.sp
If these settings are used multiple times in the same unit all the specified programs are attached\&. If an empty string is assigned to these settings the program list is reset and all previous specified programs ignored\&.
.sp
If the path
\fIBPF_FS_PROGRAM_PATH\fR
in
\fIIPIngressFilterPath=\fR
assignment is already being handled by
\fIBPFProgram=\fR
ingress hook, e\&.g\&.
\fIBPFProgram=\fR\fBingress\fR:\fIBPF_FS_PROGRAM_PATH\fR, the assignment will be still considered valid and the program will be attached to a cgroup\&. Same for
\fIIPEgressFilterPath=\fR
path and
\fBegress\fR
hook\&.
.sp
Note that for socket\-activated services, the IP filter programs configured on the socket unit apply to all sockets associated with it directly, but not to any sockets created by the ultimately activated services for it\&. Conversely, the IP filter programs configured for the service are not applied to any sockets passed into the service via socket activation\&. Thus, it is usually a good idea, to replicate the IP filter programs on both the socket and the service unit, however it often makes sense to maintain one configuration more open and the other one more restricted, depending on the use case\&.
.sp
Note that these settings might not be supported on some systems (for example if eBPF control group support is not enabled in the underlying kernel or container manager)\&. These settings will fail the service in that case\&. If compatibility with such systems is desired it is hence recommended to attach your filter manually (requires
\fIDelegate=\fR\fByes\fR) instead of using this setting\&.
.sp
Added in version 243\&.
.RE
.PP
\fIBPFProgram=\fR\fI\fItype\fR\fR\fI:\fR\fI\fIprogram\-path\fR\fR
.RS 4
\fIBPFProgram=\fR
allows attaching custom BPF programs to the cgroup of a unit\&. (This generalizes the functionality exposed via
\fIIPEgressFilterPath=\fR
and
\fIIPIngressFilterPath=\fR
for other hooks\&.) Cgroup\-bpf hooks in the form of BPF programs loaded to the BPF filesystem are attached with cgroup\-bpf attach flags determined by the unit\&. For details about attachment types and flags see
\m[blue]\fBbpf\&.h\fR\m[]\&\s-2\u[10]\d\s+2\&. Also refer to the general
\m[blue]\fBBPF documentation\fR\m[]\&\s-2\u[11]\d\s+2\&.
.sp
The specification of BPF program consists of a pair of BPF program type and program path in the file system, with
":"
as the separator:
\fItype\fR:\fIprogram\-path\fR\&.
.sp
The BPF program type is equivalent to the BPF attach type used in
\fBbpftool\fR(8)
It may be one of
\fBegress\fR,
\fBingress\fR,
\fBsock_create\fR,
\fBsock_ops\fR,
\fBdevice\fR,
\fBbind4\fR,
\fBbind6\fR,
\fBconnect4\fR,
\fBconnect6\fR,
\fBpost_bind4\fR,
\fBpost_bind6\fR,
\fBsendmsg4\fR,
\fBsendmsg6\fR,
\fBsysctl\fR,
\fBrecvmsg4\fR,
\fBrecvmsg6\fR,
\fBgetsockopt\fR, or
\fBsetsockopt\fR\&.
.sp
The specified program path must be an absolute path referencing a BPF program inode in the bpffs file system (which generally means it must begin with
/sys/fs/bpf/)\&. If a specified program does not exist (i\&.e\&. has not been uploaded to the BPF subsystem of the kernel yet), it will not be installed but unit activation will continue (a warning will be printed to the logs)\&.
.sp
Setting
\fIBPFProgram=\fR
to an empty value makes previous assignments ineffective\&.
.sp
Multiple assignments of the same program type/path pair have the same effect as a single assignment: the program will be attached just once\&.
.sp
If BPF
\fBegress\fR
pinned to
\fIprogram\-path\fR
path is already being handled by
\fIIPEgressFilterPath=\fR,
\fIBPFProgram=\fR
assignment will be considered valid and
\fIBPFProgram=\fR
will be attached to a cgroup\&. Similarly for
\fBingress\fR
hook and
\fIIPIngressFilterPath=\fR
assignment\&.
.sp
BPF programs passed with
\fIBPFProgram=\fR
are attached to the cgroup of a unit with BPF attach flag
\fBmulti\fR, that allows further attachments of the same
\fItype\fR
within cgroup hierarchy topped by the unit cgroup\&.
.sp
Examples:
.sp
.if n \{\
.RS 4
.\}
.nf
BPFProgram=egress:/sys/fs/bpf/egress\-hook
BPFProgram=bind6:/sys/fs/bpf/sock\-addr\-hook
.fi
.if n \{\
.RE
.\}
.sp
Added in version 249\&.
.RE
.SS "Device Access"
.PP
\fIDeviceAllow=\fR
.RS 4
Control access to specific device nodes by the executed processes\&. Takes two space\-separated strings: a device node specifier followed by a combination of
\fBr\fR,
\fBw\fR,
\fBm\fR
to control
\fIr\fReading,
\fIw\fRriting, or creation of the specific device nodes by the unit (\fIm\fRknod), respectively\&. This functionality is implemented using eBPF filtering\&.
.sp
When access to
\fIall\fR
physical devices should be disallowed,
\fIPrivateDevices=\fR
may be used instead\&. See
\fBsystemd.exec\fR(5)\&.
.sp
The device node specifier is either a path to a device node in the file system, starting with
/dev/, or a string starting with either
"char\-"
or
"block\-"
followed by a device group name, as listed in
/proc/devices\&. The latter is useful to allow\-list all current and future devices belonging to a specific device group at once\&. The device group is matched according to filename globbing rules, you may hence use the
"*"
and
"?"
wildcards\&. (Note that such globbing wildcards are not available for device node path specifications!) In order to match device nodes by numeric major/minor, use device node paths in the
/dev/char/
and
/dev/block/
directories\&. However, matching devices by major/minor is generally not recommended as assignments are neither stable nor portable between systems or different kernel versions\&.
.sp
Examples:
/dev/sda5
is a path to a device node, referring to an ATA or SCSI block device\&.
"char\-pts"
and
"char\-alsa"
are specifiers for all pseudo TTYs and all ALSA sound devices, respectively\&.
"char\-cpu/*"
is a specifier matching all CPU related device groups\&.
.sp
Note that allow lists defined this way should only reference device groups which are resolvable at the time the unit is started\&. Any device groups not resolvable then are not added to the device allow list\&. In order to work around this limitation, consider extending service units with a pair of
\fBAfter=modprobe@xyz\&.service\fR
and
\fBWants=modprobe@xyz\&.service\fR
lines that load the necessary kernel module implementing the device group if missing\&. Example:
.sp
.if n \{\
.RS 4
.\}
.nf
\&...
[Unit]
Wants=modprobe@loop\&.service
After=modprobe@loop\&.service

[Service]
DeviceAllow=block\-loop
DeviceAllow=/dev/loop\-control
\&...
.fi
.if n \{\
.RE
.\}
.sp
This option cannot be bypassed by prefixing
"+"
to the executable path in the service unit, as it applies to the whole control group\&.
.sp
Added in version 208\&.
.RE
.PP
\fIDevicePolicy=auto|closed|strict\fR
.RS 4
Control the policy for allowing device access:
.PP
\fBstrict\fR
.RS 4
means to only allow types of access that are explicitly specified\&.
.sp
Added in version 208\&.
.RE
.PP
\fBclosed\fR
.RS 4
in addition, allows access to standard pseudo devices including
/dev/null,
/dev/zero,
/dev/full,
/dev/random, and
/dev/urandom\&.
.sp
Added in version 208\&.
.RE
.PP
\fBauto\fR
.RS 4
in addition, allows access to all devices if no explicit
\fIDeviceAllow=\fR
is present\&. This is the default\&.
.sp
Added in version 208\&.
.RE
.sp
This option cannot be bypassed by prefixing
"+"
to the executable path in the service unit, as it applies to the whole control group\&.
.sp
Added in version 208\&.
.RE
.SS "Control Group Management"
.PP
\fISlice=\fR
.RS 4
The name of the slice unit to place the unit in\&. Defaults to
system\&.slice
for all non\-instantiated units of all unit types (except for slice units themselves see below)\&. Instance units are by default placed in a subslice of
system\&.slice
that is named after the template name\&.
.sp
This option may be used to arrange systemd units in a hierarchy of slices each of which might have resource settings applied\&.
.sp
For units of type slice, the only accepted value for this setting is the parent slice\&. Since the name of a slice unit implies the parent slice, it is hence redundant to ever set this parameter directly for slice units\&.
.sp
Special care should be taken when relying on the default slice assignment in templated service units that have
\fIDefaultDependencies=no\fR
set, see
\fBsystemd.service\fR(5), section "Default Dependencies" for details\&.
.sp
Added in version 208\&.
.RE
.PP
\fIDelegate=\fR
.RS 4
Turns on delegation of further resource control partitioning to processes of the unit\&. Units where this is enabled may create and manage their own private subhierarchy of control groups below the control group of the unit itself\&. For unprivileged services (i\&.e\&. those using the
\fIUser=\fR
setting) the unit\*(Aqs control group will be made accessible to the relevant user\&.
.sp
When enabled the service manager will refrain from manipulating control groups or moving processes below the unit\*(Aqs control group, so that a clear concept of ownership is established: the control group tree at the level of the unit\*(Aqs control group and above (i\&.e\&. towards the root control group) is owned and managed by the service manager of the host, while the control group tree below the unit\*(Aqs control group is owned and managed by the unit itself\&.
.sp
Takes either a boolean argument or a (possibly empty) list of control group controller names\&. If true, delegation is turned on, and all supported controllers are enabled for the unit, making them available to the unit\*(Aqs processes for management\&. If false, delegation is turned off entirely (and no additional controllers are enabled)\&. If set to a list of controllers, delegation is turned on, and the specified controllers are enabled for the unit\&. Assigning the empty string will enable delegation, but reset the list of controllers, and all assignments prior to this will have no effect\&. Note that additional controllers other than the ones specified might be made available as well, depending on configuration of the containing slice unit or other units contained in it\&. Defaults to false\&.
.sp
Note that controller delegation to less privileged code is only safe on the unified control group hierarchy\&. Accordingly, access to the specified controllers will not be granted to unprivileged services on the legacy hierarchy, even when requested\&.
.sp
The following controller names may be specified:
\fBcpu\fR,
\fBcpuacct\fR,
\fBcpuset\fR,
\fBio\fR,
\fBblkio\fR,
\fBmemory\fR,
\fBdevices\fR,
\fBpids\fR,
\fBbpf\-firewall\fR, and
\fBbpf\-devices\fR\&.
.sp
Not all of these controllers are available on all kernels however, and some are specific to the unified hierarchy while others are specific to the legacy hierarchy\&. Also note that the kernel might support further controllers, which aren\*(Aqt covered here yet as delegation is either not supported at all for them or not defined cleanly\&.
.sp
Note that because of the hierarchical nature of cgroup hierarchy, any controllers that are delegated will be enabled for the parent and sibling units of the unit with delegation\&.
.sp
For further details on the delegation model consult
\m[blue]\fBControl Group APIs and Delegation\fR\m[]\&\s-2\u[12]\d\s+2\&.
.sp
Added in version 218\&.
.RE
.PP
\fIDelegateSubgroup=\fR
.RS 4
Place unit processes in the specified subgroup of the unit\*(Aqs control group\&. Takes a valid control group name (not a path!) as parameter, or an empty string to turn this feature off\&. Defaults to off\&. The control group name must be usable as filename and avoid conflicts with the kernel\*(Aqs control group attribute files (i\&.e\&.
cgroup\&.procs
is not an acceptable name, since the kernel exposes a native control group attribute file by that name)\&. This option has no effect unless control group delegation is turned on via
\fIDelegate=\fR, see above\&. Note that this setting only applies to "main" processes of a unit, i\&.e\&. for services to
\fIExecStart=\fR, but not for
\fIExecReload=\fR
and similar\&. If delegation is enabled, the latter are always placed inside a subgroup named
\&.control\&. The specified subgroup is automatically created (and potentially ownership is passed to the unit\*(Aqs configured user/group) when a process is started in it\&.
.sp
This option is useful to avoid manually moving the invoked process into a subgroup after it has been started\&. Since no processes should live in inner nodes of the control group tree it\*(Aqs almost always necessary to run the main ("supervising") process of a unit that has delegation turned on in a subgroup\&.
.sp
Added in version 254\&.
.RE
.PP
\fIDisableControllers=\fR
.RS 4
Disables controllers from being enabled for a unit\*(Aqs children\&. If a controller listed is already in use in its subtree, the controller will be removed from the subtree\&. This can be used to avoid configuration in child units from being able to implicitly or explicitly enable a controller\&. Defaults to empty\&.
.sp
Multiple controllers may be specified, separated by spaces\&. You may also pass
\fIDisableControllers=\fR
multiple times, in which case each new instance adds another controller to disable\&. Passing
\fIDisableControllers=\fR
by itself with no controller name present resets the disabled controller list\&.
.sp
It may not be possible to disable a controller after units have been started, if the unit or any child of the unit in question delegates controllers to its children, as any delegated subtree of the cgroup hierarchy is unmanaged by systemd\&.
.sp
The following controller names may be specified:
\fBcpu\fR,
\fBcpuacct\fR,
\fBcpuset\fR,
\fBio\fR,
\fBblkio\fR,
\fBmemory\fR,
\fBdevices\fR,
\fBpids\fR,
\fBbpf\-firewall\fR, and
\fBbpf\-devices\fR\&.
.sp
Added in version 240\&.
.RE
.SS "Memory Pressure Control"
.PP
\fIManagedOOMSwap=auto|kill\fR, \fIManagedOOMMemoryPressure=auto|kill\fR
.RS 4
Specifies how
\fBsystemd-oomd.service\fR(8)
will act on this unit\*(Aqs cgroups\&. Defaults to
\fBauto\fR\&.
.sp
When set to
\fBkill\fR, the unit becomes a candidate for monitoring by
\fBsystemd\-oomd\fR\&. If the cgroup passes the limits set by
\fBoomd.conf\fR(5)
or the unit configuration,
\fBsystemd\-oomd\fR
will select a descendant cgroup and send
\fBSIGKILL\fR
to all of the processes under it\&. You can find more details on candidates and kill behavior at
\fBsystemd-oomd.service\fR(8)
and
\fBoomd.conf\fR(5)\&.
.sp
Setting either of these properties to
\fBkill\fR
will also result in
\fIAfter=\fR
and
\fIWants=\fR
dependencies on
systemd\-oomd\&.service
unless
\fIDefaultDependencies=no\fR\&.
.sp
When set to
\fBauto\fR,
\fBsystemd\-oomd\fR
will not actively use this cgroup\*(Aqs data for monitoring and detection\&. However, if an ancestor cgroup has one of these properties set to
\fBkill\fR, a unit with
\fBauto\fR
can still be a candidate for
\fBsystemd\-oomd\fR
to terminate\&.
.sp
Added in version 247\&.
.RE
.PP
\fIManagedOOMMemoryPressureLimit=\fR
.RS 4
Overrides the default memory pressure limit set by
\fBoomd.conf\fR(5)
for this unit (cgroup)\&. Takes a percentage value between 0% and 100%, inclusive\&. This property is ignored unless
\fIManagedOOMMemoryPressure=\fR\fBkill\fR\&. Defaults to 0%, which means to use the default set by
\fBoomd.conf\fR(5)\&.
.sp
Added in version 247\&.
.RE
.PP
\fIManagedOOMPreference=none|avoid|omit\fR
.RS 4
Allows deprioritizing or omitting this unit\*(Aqs cgroup as a candidate when
\fBsystemd\-oomd\fR
needs to act\&. Requires support for extended attributes (see
\fBxattr\fR(7)) in order to use
\fBavoid\fR
or
\fBomit\fR\&.
.sp
When calculating candidates to relieve swap usage,
\fBsystemd\-oomd\fR
will only respect these extended attributes if the unit\*(Aqs cgroup is owned by root\&.
.sp
When calculating candidates to relieve memory pressure,
\fBsystemd\-oomd\fR
will only respect these extended attributes if the unit\*(Aqs cgroup is owned by root, or if the unit\*(Aqs cgroup owner, and the owner of the monitored ancestor cgroup are the same\&. For example, if
\fBsystemd\-oomd\fR
is calculating candidates for
\-\&.slice, then extended attributes set on descendants of
/user\&.slice/user\-1000\&.slice/user@1000\&.service/
will be ignored because the descendants are owned by UID 1000, and
\-\&.slice
is owned by UID 0\&. But, if calculating candidates for
/user\&.slice/user\-1000\&.slice/user@1000\&.service/, then extended attributes set on the descendants would be respected\&.
.sp
If this property is set to
\fBavoid\fR, the service manager will convey this to
\fBsystemd\-oomd\fR, which will only select this cgroup if there are no other viable candidates\&.
.sp
If this property is set to
\fBomit\fR, the service manager will convey this to
\fBsystemd\-oomd\fR, which will ignore this cgroup as a candidate and will not perform any actions on it\&.
.sp
It is recommended to use
\fBavoid\fR
and
\fBomit\fR
sparingly, as it can adversely affect
\fBsystemd\-oomd\fR\*(Aqs kill behavior\&. Also note that these extended attributes are not applied recursively to cgroups under this unit\*(Aqs cgroup\&.
.sp
Defaults to
\fBnone\fR
which means
\fBsystemd\-oomd\fR
will rank this unit\*(Aqs cgroup as defined in
\fBsystemd-oomd.service\fR(8)
and
\fBoomd.conf\fR(5)\&.
.sp
Added in version 248\&.
.RE
.PP
\fIMemoryPressureWatch=\fR
.RS 4
Controls memory pressure monitoring for invoked processes\&. Takes one of
"off",
"on",
"auto"
or
"skip"\&. If
"off"
tells the service not to watch for memory pressure events, by setting the
\fI$MEMORY_PRESSURE_WATCH\fR
environment variable to the literal string
/dev/null\&. If
"on"
tells the service to watch for memory pressure events\&. This enables memory accounting for the service, and ensures the
memory\&.pressure
cgroup attribute file is accessible for reading and writing by the service\*(Aqs user\&. It then sets the
\fI$MEMORY_PRESSURE_WATCH\fR
environment variable for processes invoked by the unit to the file system path to this file\&. The threshold information configured with
\fIMemoryPressureThresholdSec=\fR
is encoded in the
\fI$MEMORY_PRESSURE_WRITE\fR
environment variable\&. If the
"auto"
value is set the protocol is enabled if memory accounting is anyway enabled for the unit, and disabled otherwise\&. If set to
"skip"
the logic is neither enabled, nor disabled and the two environment variables are not set\&.
.sp
Note that services are free to use the two environment variables, but it\*(Aqs unproblematic if they ignore them\&. Memory pressure handling must be implemented individually in each service, and usually means different things for different software\&. For further details on memory pressure handling see
\m[blue]\fBMemory Pressure Handling in systemd\fR\m[]\&\s-2\u[13]\d\s+2\&.
.sp
Services implemented using
\fBsd-event\fR(3)
may use
\fBsd_event_add_memory_pressure\fR(3)
to watch for and handle memory pressure events\&.
.sp
If not explicit set, defaults to the
\fIDefaultMemoryPressureWatch=\fR
setting in
\fBsystemd-system.conf\fR(5)\&.
.sp
Added in version 254\&.
.RE
.PP
\fIMemoryPressureThresholdSec=\fR
.RS 4
Sets the memory pressure threshold time for memory pressure monitor as configured via
\fIMemoryPressureWatch=\fR\&. Specifies the maximum allocation latency before a memory pressure event is signalled to the service, per 2s window\&. If not specified defaults to the
\fIDefaultMemoryPressureThresholdSec=\fR
setting in
\fBsystemd-system.conf\fR(5)
(which in turn defaults to 200ms)\&. The specified value expects a time unit such as
"ms"
or
"μs", see
\fBsystemd.time\fR(7)
for details on the permitted syntax\&.
.sp
Added in version 254\&.
.RE
.SS "Coredump Control"
.PP
\fICoredumpReceive=\fR
.RS 4
Takes a boolean argument\&. This setting is used to enable coredump forwarding for containers that belong to this unit\*(Aqs cgroup\&. Units with
\fICoredumpReceive=yes\fR
must also be configured with
\fIDelegate=yes\fR\&. Defaults to false\&.
.sp
When
\fBsystemd\-coredump\fR
is handling a coredump for a process from a container, if the container\*(Aqs leader process is a descendant of a cgroup with
\fICoredumpReceive=yes\fR
and
\fIDelegate=yes\fR, then
\fBsystemd\-coredump\fR
will attempt to forward the coredump to
\fBsystemd\-coredump\fR
within the container\&.
.sp
Added in version 255\&.
.RE
.SH "HISTORY"
.PP
systemd 252
.RS 4
Options for controlling the Legacy Control Group Hierarchy (\m[blue]\fBControl Groups version 1\fR\m[]\&\s-2\u[14]\d\s+2) are now fully deprecated:
\fICPUShares=\fR\fI\fIweight\fR\fR,
\fIStartupCPUShares=\fR\fI\fIweight\fR\fR,
\fIMemoryLimit=\fR\fI\fIbytes\fR\fR,
\fIBlockIOAccounting=\fR,
\fIBlockIOWeight=\fR\fI\fIweight\fR\fR,
\fIStartupBlockIOWeight=\fR\fI\fIweight\fR\fR,
\fIBlockIODeviceWeight=\fR\fI\fIdevice\fR\fR\fI \fR\fI\fIweight\fR\fR,
\fIBlockIOReadBandwidth=\fR\fI\fIdevice\fR\fR\fI \fR\fI\fIbytes\fR\fR,
\fIBlockIOWriteBandwidth=\fR\fI\fIdevice\fR\fR\fI \fR\fI\fIbytes\fR\fR\&. Please switch to the unified cgroup hierarchy\&.
.sp
Added in version 252\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1), \fBsystemd-system.conf\fR(5), \fBsystemd.unit\fR(5), \fBsystemd.service\fR(5), \fBsystemd.slice\fR(5), \fBsystemd.scope\fR(5), \fBsystemd.socket\fR(5), \fBsystemd.mount\fR(5), \fBsystemd.swap\fR(5), \fBsystemd.exec\fR(5), \fBsystemd.directives\fR(7), \fBsystemd.special\fR(7), \fBsystemd-oomd.service\fR(8), The documentation for control groups and specific controllers in the Linux kernel: \m[blue]\fBControl Groups v2\fR\m[]\&\s-2\u[2]\d\s+2
.SH "NOTES"
.IP " 1." 4
New Control Group Interfaces
.RS 4
\%https://systemd.io/CONTROL_GROUP_INTERFACE
.RE
.IP " 2." 4
Control Groups v2
.RS 4
\%https://docs.kernel.org/admin-guide/cgroup-v2.html
.RE
.IP " 3." 4
CFS Scheduler
.RS 4
\%https://docs.kernel.org/scheduler/sched-design-CFS.html
.RE
.IP " 4." 4
CFS Bandwidth Control
.RS 4
\%https://docs.kernel.org/scheduler/sched-bwc.html
.RE
.IP " 5." 4
Memory Interface Files
.RS 4
\%https://docs.kernel.org/admin-guide/cgroup-v2.html#memory-interface-files
.RE
.IP " 6." 4
Zswap
.RS 4
\%https://docs.kernel.org/admin-guide/mm/zswap.html
.RE
.IP " 7." 4
pids controller
.RS 4
\%https://docs.kernel.org/admin-guide/cgroup-v2.html#pid
.RE
.IP " 8." 4
IO Interface Files
.RS 4
\%https://docs.kernel.org/admin-guide/cgroup-v2.html#io-interface-files
.RE
.IP " 9." 4
NFT
.RS 4
\%https://netfilter.org/projects/nftables/index.html
.RE
.IP "10." 4
bpf.h
.RS 4
\%https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/include/uapi/linux/bpf.h
.RE
.IP "11." 4
BPF documentation
.RS 4
\%https://docs.kernel.org/bpf/
.RE
.IP "12." 4
Control Group APIs and Delegation
.RS 4
\%https://systemd.io/CGROUP_DELEGATION
.RE
.IP "13." 4
Memory Pressure Handling in systemd
.RS 4
\%https://systemd.io/MEMORY_PRESSURE
.RE
.IP "14." 4
Control Groups version 1
.RS 4
\%https://docs.kernel.org/admin-guide/cgroup-v1/index.html
.RE
