'\" t
.TH "BOOTCTL" "1" "" "systemd 256.4" "bootctl"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
bootctl \- Control EFI firmware boot settings and manage boot loader
.SH "SYNOPSIS"
.HP \w'\fBbootctl\fR\ 'u
\fBbootctl\fR [OPTIONS...] {COMMAND}
.SH "DESCRIPTION"
.PP
\fBbootctl\fR
can check the EFI firmware and boot loader status, list and manage available boot loaders and boot loader entries, and install, update, or remove the
\fBsystemd-boot\fR(7)
boot loader on the current system\&.
.SH "GENERIC EFI FIRMWARE/BOOT LOADER COMMANDS"
.PP
These commands are available on any EFI system, regardless of the boot loader used\&.
.PP
\fBstatus\fR
.RS 4
Shows brief information about the system firmware, the boot loader that was used to boot the system, the boot loaders currently available in the ESP, the boot loaders listed in the firmware\*(Aqs list of boot loaders and the current default boot loader entry\&. If no command is specified, this is the implied default\&.
.sp
See the example below for details of the output\&.
.sp
Added in version 239\&.
.RE
.PP
\fBreboot\-to\-firmware\fR [\fIBOOL\fR]
.RS 4
Query or set the "Reboot\-Into\-Firmware\-Setup" flag of the EFI firmware\&. Takes a boolean argument which controls whether to show the firmware setup on next system reboot\&. If the argument is omitted shows the current status of the flag, or whether the flag is supported\&. This controls the same flag as
\fBsystemctl reboot \-\-firmware\-setup\fR, but is more low\-level and allows setting the flag independently from actually requesting a reboot\&.
.sp
Hint: use
\fBsystemctl reboot \-\-firmware\-setup\fR
to reboot into firmware setup once\&. See
\fBsystemctl\fR(1)
for details\&.
.sp
Added in version 251\&.
.RE
.SH "BOOT LOADER SPECIFICATION COMMANDS"
.PP
These commands are available for all boot loaders that implement the
\m[blue]\fBBoot Loader Specification\fR\m[]\&\s-2\u[1]\d\s+2, such as
\fBsystemd\-boot\fR\&.
.PP
\fBlist\fR
.RS 4
Shows all available boot loader entries implementing the
\m[blue]\fBBoot Loader Specification\fR\m[]\&\s-2\u[1]\d\s+2, as well as any other entries discovered or automatically generated by a boot loader implementing the
\m[blue]\fBBoot Loader Interface\fR\m[]\&\s-2\u[2]\d\s+2\&. JSON output may be requested with
\fB\-\-json=\fR\&.
.sp
See the example below for details of the output\&.
.sp
Added in version 239\&.
.RE
.PP
\fBunlink\fR \fIID\fR
.RS 4
Removes a boot loader entry including the files it refers to\&. Takes a single boot loader entry ID string or a glob pattern as argument\&. Referenced files such as kernel or initrd are only removed if no other entry refers to them\&.
.sp
Added in version 253\&.
.RE
.PP
\fBcleanup\fR
.RS 4
Removes files from the ESP and XBOOTLDR partitions that belong to the entry token but are not referenced in any boot loader entries\&.
.sp
Added in version 253\&.
.RE
.SH "BOOT LOADER INTERFACE COMMANDS"
.PP
These commands are available for all boot loaders that implement the
\m[blue]\fBBoot Loader Specification\fR\m[]\&\s-2\u[1]\d\s+2
and the
\m[blue]\fBBoot Loader Interface\fR\m[]\&\s-2\u[2]\d\s+2, such as
\fBsystemd\-boot\fR\&.
.PP
\fBset\-default\fR \fIID\fR, \fBset\-oneshot\fR \fIID\fR
.RS 4
Sets the default boot loader entry\&. Takes a single boot loader entry ID string or a glob pattern as argument\&. The
\fBset\-oneshot\fR
command will set the default entry only for the next boot, the
\fBset\-default\fR
will set it persistently for all future boots\&.
.sp
\fBbootctl list\fR
can be used to list available boot loader entries and their IDs\&.
.sp
In addition, the boot loader entry ID may be specified as one of:
\fB@default\fR,
\fB@oneshot\fR
or
\fB@current\fR, which correspond to the current default boot loader entry for all future boots, the current default boot loader entry for the next boot, and the currently booted boot loader entry\&. These special IDs are resolved to the current values of the EFI variables
\fILoaderEntryDefault\fR,
\fILoaderEntryOneShot\fR
and
\fILoaderEntrySelected\fR, see
\m[blue]\fBBoot Loader Specification\fR\m[]\&\s-2\u[1]\d\s+2
for details\&. These special IDs are primarily useful as a quick way to persistently make the currently booted boot loader entry the default choice, or to upgrade the default boot loader entry for the next boot to the default boot loader entry for all future boots, but may be used for other operations too\&.
.sp
If set to
\fB@saved\fR
the chosen entry will be saved as an EFI variable on every boot and automatically selected the next time the boot loader starts\&.
.sp
When an empty string ("") is specified as the ID, then the corresponding EFI variable will be unset\&.
.sp
Hint: use
\fBsystemctl reboot \-\-boot\-loader\-entry=\fR\fB\fIID\fR\fR
to reboot into a specific boot entry and
\fBsystemctl reboot \-\-boot\-loader\-menu=\fR\fB\fItimeout\fR\fR
to reboot into the boot loader menu once\&. See
\fBsystemctl\fR(1)
for details\&.
.sp
Added in version 240\&.
.RE
.PP
\fBset\-timeout\fR \fITIMEOUT\fR, \fBset\-timeout\-oneshot\fR \fITIMEOUT\fR
.RS 4
Sets the boot loader menu timeout in seconds\&. The
\fBset\-timeout\-oneshot\fR
command will set the timeout only for the next boot\&. See
\fBsystemd.time\fR(7)
for details about the syntax of time spans\&.
.sp
If this is set to
\fBmenu\-disabled\fR
or
\fBmenu\-hidden\fR
or
\fB0\fR, no menu is shown and the default entry will be booted immediately, while setting this to
\fBmenu\-force\fR
disables the timeout while always showing the menu\&. When an empty string ("") is specified the bootloader will revert to its default menu timeout\&.
.sp
Added in version 250\&.
.RE
.SH "SYSTEMD\-BOOT COMMANDS"
.PP
These commands manage the
\fBsystemd\-boot\fR
EFI boot loader, and do not work in conjunction with other boot loaders\&.
.PP
\fBinstall\fR
.RS 4
Installs
\fBsystemd\-boot\fR
into the EFI system partition\&. A copy of
\fBsystemd\-boot\fR
will be stored as the EFI default/fallback loader at
\fIESP\fR/EFI/BOOT/BOOT*\&.EFI\&. The boot loader is then added to the top of the firmware\*(Aqs boot loader list\&.
.sp
Added in version 239\&.
.RE
.PP
\fBupdate\fR
.RS 4
Updates all installed versions of
\fBsystemd-boot\fR(7), if the available version is newer than the version installed in the EFI system partition\&. This also includes the EFI default/fallback loader at
\fIESP\fR/EFI/BOOT/BOOT*\&.EFI\&. The boot loader is then added to end of the firmware\*(Aqs boot loader list if missing\&.
.sp
Added in version 239\&.
.RE
.PP
\fBremove\fR
.RS 4
Removes all installed versions of
\fBsystemd\-boot\fR
from the EFI system partition and the firmware\*(Aqs boot loader list\&.
.sp
Added in version 239\&.
.RE
.PP
\fBis\-installed\fR
.RS 4
Checks whether
\fBsystemd\-boot\fR
is installed in the ESP\&. Note that a single ESP might host multiple boot loaders; this hence checks whether
\fBsystemd\-boot\fR
is one (of possibly many) installed boot loaders \(em and neither whether it is the default nor whether it is registered in any EFI variables\&.
.sp
Added in version 243\&.
.RE
.PP
\fBrandom\-seed\fR
.RS 4
Generates a random seed and stores it in the EFI System Partition (ESP), for use by the
\fBsystemd\-boot\fR
boot loader\&. If a random seed already exists in the ESP it is refreshed\&. Also generates a random \*(Aqsystem token\*(Aq and stores it persistently as an EFI variable, if one has not been set before\&. If the boot loader finds the random seed in the ESP and the system token in the EFI variable it will derive a random seed to pass to the OS and a new seed to store in the ESP from the combination of both\&. The random seed passed to the OS is credited to the kernel\*(Aqs entropy pool by the system manager during early boot, and permits userspace to boot up with an entropy pool fully initialized very early on\&. Also see
\fBsystemd-boot-random-seed.service\fR(8)\&.
.sp
See
\m[blue]\fBRandom Seeds\fR\m[]\&\s-2\u[3]\d\s+2
for further information\&.
.sp
Added in version 243\&.
.RE
.SH "KERNEL IMAGE COMMANDS"
.PP
\fBkernel\-identify\fR \fIkernel\fR
.RS 4
Takes a kernel image as argument\&. Checks what kind of kernel the image is\&. Returns one of
"uki",
"pe", and
"unknown"\&.
.sp
Added in version 253\&.
.RE
.PP
\fBkernel\-inspect\fR \fIkernel\fR
.RS 4
Takes a kernel image as argument\&. Prints details about the image\&.
.sp
Added in version 253\&.
.RE
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-\-esp\-path=\fR
.RS 4
Path to the EFI System Partition (ESP)\&. If not specified,
/efi/,
/boot/, and
/boot/efi/
are checked in turn\&. It is recommended to mount the ESP to
/efi/, if possible\&.
.RE
.PP
\fB\-\-boot\-path=\fR
.RS 4
Path to the Extended Boot Loader partition, as defined in the
\m[blue]\fBBoot Loader Specification\fR\m[]\&\s-2\u[1]\d\s+2\&. If not specified,
/boot/
is checked\&. It is recommended to mount the Extended Boot Loader partition to
/boot/, if possible\&.
.RE
.PP
\fB\-\-root=\fR\fB\fIroot\fR\fR
.RS 4
Takes a directory path as an argument\&. All paths will be prefixed with the given alternate
\fIroot\fR
path, including config search paths\&.
.sp
Added in version 252\&.
.RE
.PP
\fB\-\-image=\fR\fB\fIimage\fR\fR
.RS 4
Takes a path to a disk image file or block device node\&. If specified, all operations are applied to file system in the indicated disk image\&. This option is similar to
\fB\-\-root=\fR, but operates on file systems stored in disk images or block devices\&. The disk image should either contain just a file system or a set of file systems within a GPT partition table, following the
\m[blue]\fBDiscoverable Partitions Specification\fR\m[]\&\s-2\u[4]\d\s+2\&. For further information on supported disk images, see
\fBsystemd-nspawn\fR(1)\*(Aqs switch of the same name\&.
.sp
Added in version 252\&.
.RE
.PP
\fB\-\-image\-policy=\fR\fB\fIpolicy\fR\fR
.RS 4
Takes an image policy string as argument, as per
\fBsystemd.image-policy\fR(7)\&. The policy is enforced when operating on the disk image specified via
\fB\-\-image=\fR, see above\&. If not specified defaults to the
"*"
policy, i\&.e\&. all recognized file systems in the image are used\&.
.RE
.PP
\fB\-\-install\-source=\fR
.RS 4
When installing binaries with
\fB\-\-root=\fR
or
\fB\-\-image=\fR, selects where to source them from\&. Takes one of
"auto"
(the default),
"image"
or
"host"\&. With
"auto"
binaries will be picked from the specified directory or image, and if not found they will be picked from the host\&. With
"image"
or
"host"
no fallback search will be performed if the binaries are not found in the selected source\&.
.sp
Added in version 252\&.
.RE
.PP
\fB\-p\fR, \fB\-\-print\-esp\-path\fR
.RS 4
This option modifies the behaviour of
\fBstatus\fR\&. Only prints the path to the EFI System Partition (ESP) to standard output and exits\&.
.sp
Added in version 236\&.
.RE
.PP
\fB\-x\fR, \fB\-\-print\-boot\-path\fR
.RS 4
This option modifies the behaviour of
\fBstatus\fR\&. Only prints the path to the Extended Boot Loader partition if it exists, and the path to the ESP otherwise to standard output and exit\&. This command is useful to determine where to place boot loader entries, as they are preferably placed in the Extended Boot Loader partition if it exists and in the ESP otherwise\&.
.sp
Boot Loader Specification Type #1 entries should generally be placed in the directory
"$(bootctl \-x)/loader/entries/"\&. Existence of that directory may also be used as indication that boot loader entry support is available on the system\&. Similarly, Boot Loader Specification Type #2 entries should be placed in the directory
"$(bootctl \-x)/EFI/Linux/"\&.
.sp
Note that this option (similarly to the
\fB\-\-print\-esp\-path\fR
option mentioned above), is available independently from the boot loader used, i\&.e\&. also without
\fBsystemd\-boot\fR
being installed\&.
.sp
Added in version 242\&.
.RE
.PP
\fB\-R\fR, \fB\-\-print\-root\-device\fR
.RS 4
Print the path to the block device node backing the root file system of the local OS\&. This prints a path such as
/dev/nvme0n1p5\&. If the root file system is backed by dm\-crypt/LUKS or dm\-verity the underlying block device is returned\&. If the root file system is backed by multiple block devices (as supported by btrfs) the operation will fail\&. If the switch is specified twice (i\&.e\&.
\fB\-RR\fR) and the discovered block device is a partition device the "whole" block device it belongs to is determined and printed (e\&.g\&.
/dev/nvme0n1)\&. If the root file system is
"tmpfs"
(or a similar in\-memory file system), the block device backing
/usr/
is returned if applicable\&. If the root file system is a network file system (e\&.g\&. NFS, CIFS) the operation will fail\&.
.sp
Added in version 254\&.
.RE
.PP
\fB\-\-no\-variables\fR
.RS 4
Do not touch the firmware\*(Aqs boot loader list stored in EFI variables\&.
.sp
Added in version 220\&.
.RE
.PP
\fB\-\-graceful\fR
.RS 4
Ignore failure when the EFI System Partition cannot be found, when EFI variables cannot be written, or a different or newer boot loader is already installed\&. Currently only applies to
\fBis\-installed\fR,
\fBupdate\fR, and
\fBrandom\-seed\fR
verbs\&.
.sp
Added in version 244\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Suppress printing of the results of various commands and also the hints about ESP being unavailable\&.
.sp
Added in version 251\&.
.RE
.PP
\fB\-\-make\-entry\-directory=yes|no\fR
.RS 4
Controls creation and deletion of the
\m[blue]\fBBoot Loader Specification\fR\m[]\&\s-2\u[1]\d\s+2
Type #1 entry directory on the file system containing resources such as kernel and initrd images during
\fBinstall\fR
and
\fBremove\fR, respectively\&. The directory is named after the entry token, as specified with
\fB\-\-entry\-token=\fR
parameter described below, and is placed immediately below the
\fI$BOOT\fR
root directory (i\&.e\&. beneath the file system returned by the
\fB\-\-print\-boot\-path\fR
option, see above)\&. Defaults to
"no"\&.
.sp
Added in version 251\&.
.RE
.PP
\fB\-\-entry\-token=\fR
.RS 4
Controls how to name and identify boot loader entries for this OS installation\&. Accepted during
\fBinstall\fR, and takes one of
"auto",
"machine\-id",
"os\-id",
"os\-image\-id"
or an arbitrary string prefixed by
"literal:"
as argument\&.
.sp
If set to
\fBmachine\-id\fR
the entries are named after the machine ID of the running system (e\&.g\&.
"b0e793a9baf14b5fa13ecbe84ff637ac")\&. See
\fBmachine-id\fR(5)
for details about the machine ID concept and file\&.
.sp
If set to
\fBos\-id\fR
the entries are named after the OS ID of the running system, i\&.e\&. the
\fIID=\fR
field of
\fBos-release\fR(5)
(e\&.g\&.
"fedora")\&. Similarly, if set to
\fBos\-image\-id\fR
the entries are named after the OS image ID of the running system, i\&.e\&. the
\fIIMAGE_ID=\fR
field of
os\-release
(e\&.g\&.
"vendorx\-cashier\-system")\&.
.sp
If set to
\fBauto\fR
(the default), the
/etc/kernel/entry\-token
file will be read if it exists, and the stored value used\&. Otherwise if the local machine ID is initialized it is used\&. Otherwise
\fIIMAGE_ID=\fR
from
os\-release
will be used, if set\&. Otherwise,
\fIID=\fR
from
os\-release
will be used, if set\&.
.sp
Unless set to
"machine\-id", or when
\fB\-\-make\-entry\-directory=yes\fR
is used the selected token string is written to a file
/etc/kernel/entry\-token, to ensure it will be used for future entries\&. This file is also read by
\fBkernel-install\fR(8), in order to identify under which name to generate boot loader entries for newly installed kernels, or to determine the entry names for removing old ones\&.
.sp
Using the machine ID for naming the entries is generally preferable, however there are cases where using the other identifiers is a good option\&. Specifically: if the identification data that the machine ID entails shall not be stored on the (unencrypted)
\fI$BOOT\fR
partition, or if the ID shall be generated on first boot and is not known when the entries are prepared\&. Note that using the machine ID has the benefit that multiple parallel installations of the same OS can coexist on the same medium, and they can update their boot loader entries independently\&. When using another identifier (such as the OS ID or the OS image ID), parallel installations of the same OS would try to use the same entry name\&. To support parallel installations, the installer must use a different entry token when adding a second installation\&.
.sp
Added in version 251\&.
.RE
.PP
\fB\-\-all\-architectures\fR
.RS 4
Install binaries for all supported EFI architectures (this implies
\fB\-\-no\-variables\fR)\&.
.sp
Added in version 252\&.
.RE
.PP
\fB\-\-efi\-boot\-option\-description=\fR
.RS 4
Description of the entry added to the firmware\*(Aqs boot option list\&. Defaults to
"Linux Boot Manager"\&.
.sp
Using the default entry name
"Linux Boot Manager"
is generally preferable as only one bootloader installed to a single ESP partition should be used to boot any number of OS installations found on the various disks installed in the system\&. Specifically distributions should not use this flag to install a branded entry in the boot option list\&. However in situations with multiple disks, each with their own ESP partition, it can be beneficial to make it easier to identify the bootloader being used in the firmware\*(Aqs boot option menu\&.
.sp
Added in version 252\&.
.RE
.PP
\fB\-\-dry\-run\fR
.RS 4
Dry run for
\fBunlink\fR
and
\fBcleanup\fR\&.
.sp
In dry run mode, the unlink and cleanup operations only print the files that would get deleted without actually deleting them\&.
.sp
Added in version 253\&.
.RE
.PP
\fB\-\-no\-pager\fR
.RS 4
Do not pipe output into a pager\&.
.RE
.PP
\fB\-\-json=\fR\fB\fIMODE\fR\fR
.RS 4
Shows output formatted as JSON\&. Expects one of
"short"
(for the shortest possible output without any redundant whitespace or line breaks),
"pretty"
(for a pretty version of the same, with indentation and line breaks) or
"off"
(to turn off JSON output, the default)\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.SH "SIGNED \&.EFI FILES"
.PP
\fBbootctl\fR
\fBinstall\fR
and
\fBupdate\fR
will look for a
\fBsystemd\-boot\fR
file ending with the
"\&.efi\&.signed"
suffix first, and copy that instead of the normal
"\&.efi"
file\&. This allows distributions or end\-users to provide signed images for UEFI SecureBoot\&.
.SH "EXIT STATUS"
.PP
On success, 0 is returned, a non\-zero failure code otherwise\&.
\fBbootctl \-\-print\-root\-device\fR
returns exit status 80 in case the root file system is not backed by single block device, and other non\-zero exit statuses on other errors\&.
.SH "ENVIRONMENT"
.PP
If
\fI$SYSTEMD_RELAX_ESP_CHECKS=1\fR
is set the validation checks for the ESP are relaxed, and the path specified with
\fB\-\-esp\-path=\fR
may refer to any kind of file system on any kind of partition\&.
.PP
Similarly,
\fI$SYSTEMD_RELAX_XBOOTLDR_CHECKS=1\fR
turns off some validation checks for the Extended Boot Loader partition\&.
.SH "EXAMPLES"
.PP
\fBExample\ \&1.\ \&Output from status and list\fR
.sp
.if n \{\
.RS 4
.\}
.nf
$ \fBbootctl status\fR
System:
     Firmware: UEFI 2\&.40 (\fIfirmware\-version\fR)  ← firmware vendor and version
  Secure Boot: disabled (setup)              ← Secure Boot status
 TPM2 Support: yes
 Boot into FW: supported                     ← does the firmware support booting into itself

Current Boot Loader:                         ← details about sd\-boot or another boot loader
      Product: systemd\-boot \fIversion\fR            implementing the \m[blue]\fBBoot Loader Interface\fR\m[]\&\s-2\u[2]\d\s+2
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One\-shot menu timeout control
               ✓ Default entry control
               ✓ One\-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
               ✓ Load drop\-in drivers
               ✓ Boot loader sets ESP information
               ✓ Menu can be disabled
          ESP: /dev/disk/by\-partuuid/01234567\-89ab\-cdef\-dead\-beef00000000
         File: └─/EFI/systemd/systemd\-bootx64\&.efi

Random Seed:                                 ← random seed used for entropy in early boot
 Passed to OS: yes
 System Token: set
       Exists: yes

Available Boot Loaders on ESP:
          ESP: /boot/efi (/dev/disk/by\-partuuid/01234567\-89ab\-cdef\-dead\-beef00000000)
         File: └─/EFI/systemd/systemd\-bootx64\&.efi (systemd\-boot 251
         File: └─/EFI/BOOT/BOOTX64\&.EFI (systemd\-boot 251

Boot Loaders Listed in EFI Variables:
        Title: Linux Boot Manager
           ID: 0x0001
       Status: active, boot\-order
    Partition: /dev/disk/by\-partuuid/\&...
         File: └─/EFI/systemd/systemd\-bootx64\&.efi

        Title: Fedora
           ID: 0x0000
       Status: active, boot\-order
    Partition: /dev/disk/by\-partuuid/\&...
         File: └─/EFI/fedora/shimx64\&.efi

        Title: Linux\-Firmware\-Updater
           ID: 0x0002
       Status: active, boot\-order
    Partition: /dev/disk/by\-partuuid/\&...
         File: └─/EFI/fedora/fwupdx64\&.efi

Boot Loader Entries:
        $BOOT: /boot/efi (/dev/disk/by\-partuuid/01234567\-89ab\-cdef\-dead\-beef00000000)

Default Boot Loader Entry:
         type: Boot Loader Specification Type #1 (\&.conf)
        title: Fedora Linux 36 (Workstation Edition)
           id: \&...
       source: /boot/efi/loader/entries/\fIentry\-token\fR\-\fIkernel\-version\fR\&.conf
      version: \fIkernel\-version\fR
   machine\-id: \&...
        linux: /\fIentry\-token\fR/\fIkernel\-version\fR/linux
       initrd: /\fIentry\-token\fR/\fIkernel\-version\fR/initrd
      options: root=\&...
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
$ \fBbootctl list\fR
Boot Loader Entries:
         type: Boot Loader Specification Type #1 (\&.conf)
        title: Fedora Linux 36 (Workstation Edition) (default) (selected)
           id: \&...
       source: /boot/efi/loader/entries/\fIentry\-token\fR\-\fIkernel\-version\fR\&.conf
      version: \fIkernel\-version\fR
   machine\-id: \&...
        linux: /\fIentry\-token\fR/\fIkernel\-version\fR/linux
       initrd: /\fIentry\-token\fR/\fIkernel\-version\fR/initrd
      options: root=\&...

         type: Boot Loader Specification Type #2 (\&.efi)
        title: Fedora Linux 35 (Workstation Edition)
           id: \&...
       source: /boot/efi/EFI/Linux/fedora\-\fIkernel\-version\fR\&.efi
      version: \fIkernel\-version\fR
   machine\-id: \&...
        linux: /EFI/Linux/fedora\-\fIkernel\-version\fR\&.efi
      options: root=\&...

         type: Automatic
        title: Reboot Into Firmware Interface
           id: auto\-reboot\-to\-firmware\-setup
       source: /sys/firmware/efi/efivars/LoaderEntries\-4a67b082\-0a4c\-41cf\-b6c7\-440b29bb8c4f
.fi
.if n \{\
.RE
.\}
.PP
In the listing,
"(default)"
specifies the entry that will be used by default, and
"(selected)"
specifies the entry that was selected the last time (i\&.e\&. is currently running)\&.
.SH "SEE ALSO"
.PP
\fBsystemd-boot\fR(7), \m[blue]\fBBoot Loader Specification\fR\m[]\&\s-2\u[1]\d\s+2, \m[blue]\fBBoot Loader Interface\fR\m[]\&\s-2\u[2]\d\s+2, \fBsystemd-boot-random-seed.service\fR(8)
.SH "NOTES"
.IP " 1." 4
Boot Loader Specification
.RS 4
\%https://uapi-group.org/specifications/specs/boot_loader_specification
.RE
.IP " 2." 4
Boot Loader Interface
.RS 4
\%https://systemd.io/BOOT_LOADER_INTERFACE
.RE
.IP " 3." 4
Random Seeds
.RS 4
\%https://systemd.io/RANDOM_SEEDS
.RE
.IP " 4." 4
Discoverable Partitions Specification
.RS 4
\%https://uapi-group.org/specifications/specs/discoverable_partitions_specification
.RE
