'\" t
.TH "SYSTEMD\-DISSECT" "1" "" "systemd 256.4" "systemd-dissect"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-dissect, mount.ddi \- Dissect Discoverable Disk Images (DDIs)
.SH "SYNOPSIS"
.HP \w'\fBsystemd\-dissect\fR\ 'u
\fBsystemd\-dissect\fR [OPTIONS...] \fIIMAGE\fR
.HP \w'\fBsystemd\-dissect\fR\ 'u
\fBsystemd\-dissect\fR [OPTIONS...] [\-\-mount] \fIIMAGE\fR \fIPATH\fR
.HP \w'\fBsystemd\-dissect\fR\ 'u
\fBsystemd\-dissect\fR [OPTIONS...] [\-\-umount] \fIPATH\fR
.HP \w'\fBsystemd\-dissect\fR\ 'u
\fBsystemd\-dissect\fR [OPTIONS...] [\-\-attach] \fIIMAGE\fR
.HP \w'\fBsystemd\-dissect\fR\ 'u
\fBsystemd\-dissect\fR [OPTIONS...] [\-\-detach] \fIPATH\fR
.HP \w'\fBsystemd\-dissect\fR\ 'u
\fBsystemd\-dissect\fR [OPTIONS...] [\-\-list] \fIIMAGE\fR
.HP \w'\fBsystemd\-dissect\fR\ 'u
\fBsystemd\-dissect\fR [OPTIONS...] [\-\-mtree] \fIIMAGE\fR
.HP \w'\fBsystemd\-dissect\fR\ 'u
\fBsystemd\-dissect\fR [OPTIONS...] [\-\-with] \fIIMAGE\fR [\fICOMMAND\fR...]
.HP \w'\fBsystemd\-dissect\fR\ 'u
\fBsystemd\-dissect\fR [OPTIONS...] [\-\-copy\-from] \fIIMAGE\fR \fIPATH\fR [\fITARGET\fR]
.HP \w'\fBsystemd\-dissect\fR\ 'u
\fBsystemd\-dissect\fR [OPTIONS...] [\-\-copy\-to] \fIIMAGE\fR [\fISOURCE\fR] \fIPATH\fR
.HP \w'\fBsystemd\-dissect\fR\ 'u
\fBsystemd\-dissect\fR [OPTIONS...] [\-\-make\-archive] \fIIMAGE\fR [\fITARGET\fR]
.HP \w'\fBsystemd\-dissect\fR\ 'u
\fBsystemd\-dissect\fR [OPTIONS...] [\-\-discover]
.HP \w'\fBsystemd\-dissect\fR\ 'u
\fBsystemd\-dissect\fR [OPTIONS...] [\-\-validate] \fIIMAGE\fR
.SH "DESCRIPTION"
.PP
\fBsystemd\-dissect\fR
is a tool for introspecting and interacting with file system OS disk images, specifically Discoverable Disk Images (DDIs)\&. It supports four different operations:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Show general OS image information, including the image\*(Aqs
\fBos-release\fR(5)
data, machine ID, partition information and more\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Mount an OS image to a local directory\&. In this mode it will dissect the OS image and mount the included partitions according to their designation onto a directory and possibly sub\-directories\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Unmount an OS image from a local directory\&. In this mode it will recursively unmount the mounted partitions and remove the underlying loop device, including all the partition sub\-devices\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Copy files and directories in and out of an OS image\&.
.RE
.PP
The tool may operate on three types of OS images:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
OS disk images containing a GPT partition table envelope, with partitions marked according to the
\m[blue]\fBDiscoverable Partitions Specification\fR\m[]\&\s-2\u[1]\d\s+2\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
OS disk images containing just a plain file\-system without an enveloping partition table\&. (This file system is assumed to be the root file system of the OS\&.)
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
OS disk images containing a GPT or MBR partition table, with a single partition only\&. (This partition is assumed to contain the root file system of the OS\&.)
.RE
.PP
OS images may use any kind of Linux\-supported file systems\&. In addition they may make use of LUKS disk encryption, and contain Verity integrity information\&. Note that qualifying OS images may be booted with
\fBsystemd-nspawn\fR(1)\*(Aqs
\fB\-\-image=\fR
switch, and be used as root file system for system service using the
\fIRootImage=\fR
unit file setting, see
\fBsystemd.exec\fR(5)\&.
.PP
Note that the partition table shown when invoked without command switch (as listed below) does not necessarily show all partitions included in the image, but just the partitions that are understood and considered part of an OS disk image\&. Specifically, partitions of unknown types are ignored, as well as duplicate partitions (i\&.e\&. more than one per partition type), as are root and
/usr/
partitions of architectures not compatible with the local system\&. In other words: this tool will display what it operates with when mounting the image\&. To display the complete list of partitions use a tool such as
\fBfdisk\fR(8)\&.
.PP
The
\fBsystemd\-dissect\fR
command may be invoked as
\fBmount\&.ddi\fR
in which case it implements the
\fBmount\fR(8)
"external helper" interface\&. This ensures disk images compatible with
\fBsystemd\-dissect\fR
can be mounted directly by
\fBmount\fR
and
\fBfstab\fR(5)\&. For details see below\&.
.PP
In place of the image path a
"\&.v/"
versioned directory may be specified, see
\fBsystemd.v\fR(7)
for details\&.
.SH "COMMANDS"
.PP
If neither of the command switches listed below are passed the specified disk image is opened and general information about the image and the contained partitions and their use is shown\&.
.PP
\fB\-\-mount\fR, \fB\-m\fR
.RS 4
Mount the specified OS image to the specified directory\&. This will dissect the image, determine the OS root file system \(em as well as possibly other partitions \(em and mount them to the specified directory\&. If the OS image contains multiple partitions marked with the
\m[blue]\fBDiscoverable Partitions Specification\fR\m[]\&\s-2\u[1]\d\s+2
multiple nested mounts are established\&. This command expects two arguments: a path to an image file and a path to a directory where to mount the image\&.
.sp
To unmount an OS image mounted like this use the
\fB\-\-umount\fR
operation\&.
.sp
When the OS image contains LUKS encrypted or Verity integrity protected file systems appropriate volumes are automatically set up and marked for automatic disassembly when the image is unmounted\&.
.sp
The OS image may either be specified as path to an OS image stored in a regular file or may refer to block device node (in the latter case the block device must be the "whole" device, i\&.e\&. not a partition device)\&. (The other supported commands described here support this, too\&.)
.sp
All mounted file systems are checked with the appropriate
\fBfsck\fR(8)
implementation in automatic fixing mode, unless explicitly turned off (\fB\-\-fsck=no\fR) or read\-only operation is requested (\fB\-\-read\-only\fR)\&.
.sp
Note that this functionality is also available in
\fBmount\fR(8)
via a command such as
\fBmount \-t ddi myimage\&.raw targetdir/\fR, as well as in
\fBfstab\fR(5)\&. For details, see below\&.
.sp
Added in version 247\&.
.RE
.PP
\fB\-M\fR
.RS 4
This is a shortcut for
\fB\-\-mount \-\-mkdir\fR\&.
.sp
Added in version 247\&.
.RE
.PP
\fB\-\-umount\fR, \fB\-u\fR
.RS 4
Unmount an OS image from the specified directory\&. This command expects one argument: a directory where an OS image was mounted\&.
.sp
All mounted partitions will be recursively unmounted, and the underlying loop device will be removed, along with all its partition sub\-devices\&.
.sp
Added in version 252\&.
.RE
.PP
\fB\-U\fR
.RS 4
This is a shortcut for
\fB\-\-umount \-\-rmdir\fR\&.
.sp
Added in version 252\&.
.RE
.PP
\fB\-\-attach\fR
.RS 4
Attach the specified disk image to an automatically allocated loopback block device, and print the path to the loopback block device to standard output\&. This is similar to an invocation of
\fBlosetup \-\-find \-\-show\fR, but will validate the image as DDI before attaching, and derive the correct sector size to use automatically\&. Moreover, it ensures the per\-partition block devices are created before returning\&. Takes a path to a disk image file\&.
.sp
Added in version 254\&.
.RE
.PP
\fB\-\-detach\fR
.RS 4
Detach the specified disk image from a loopback block device\&. This undoes the effect of
\fB\-\-attach\fR
above\&. This expects either a path to a loopback block device as an argument, or the path to the backing image file\&. In the latter case it will automatically determine the right device to detach\&.
.sp
Added in version 254\&.
.RE
.PP
\fB\-\-list\fR, \fB\-l\fR
.RS 4
Prints the paths of all the files and directories in the specified OS image or directory to standard output\&.
.sp
Added in version 253\&.
.RE
.PP
\fB\-\-mtree\fR
.RS 4
Generates a BSD
\fBmtree\fR(8)
compatible file manifest of the specified disk image or directory\&. This is useful for comparing image contents in detail, including inode information and other metadata\&. While the generated manifest will contain detailed inode information, it currently excludes extended attributes, file system capabilities, MAC labels,
\fBchattr\fR(1)
file flags,
\fBbtrfs\fR(5)
subvolume information, and various other file metadata\&. File content information is shown via a SHA256 digest\&. Additional fields might be added in future\&. Note that inode information such as link counts, inode numbers and timestamps is excluded from the output on purpose, as it typically complicates reproducibility\&.
.sp
Added in version 253\&.
.RE
.PP
\fB\-\-with\fR
.RS 4
Runs the specified command with the specified OS image mounted\&. This will mount the image to a temporary directory, switch the current working directory to it, and invoke the specified command line as child process\&. Once the process ends it will unmount the image again, and remove the temporary directory\&. If no command is specified a shell is invoked\&. The image is mounted writable, use
\fB\-\-read\-only\fR
to switch to read\-only operation\&. The invoked process will have the
\fI$SYSTEMD_DISSECT_ROOT\fR
environment variable set, containing the absolute path name of the temporary mount point, i\&.e\&. the same directory that is set as the current working directory\&. It will also have the
\fI$SYSTEMD_DISSECT_DEVICE\fR
environment variable set, containing the absolute path name of the loop device the image was attached to\&.
.sp
Added in version 253\&.
.RE
.PP
\fB\-\-copy\-from\fR, \fB\-x\fR
.RS 4
Copies a file or directory from the specified OS image or directory into the specified location on the host file system\&. Expects three arguments: a path to an image file or directory, a source path (relative to the image\*(Aqs root directory) and a destination path (relative to the current working directory, or an absolute path, both outside of the image)\&. If the destination path is omitted or specified as dash ("\-"), the specified file is written to standard output\&. If the source path in the image file system refers to a regular file it is copied to the destination path\&. In this case access mode, extended attributes and timestamps are copied as well, but file ownership is not\&. If the source path in the image refers to a directory, it is copied to the destination path, recursively with all containing files and directories\&. In this case the file ownership is copied too\&.
.sp
Added in version 247\&.
.RE
.PP
\fB\-\-copy\-to\fR, \fB\-a\fR
.RS 4
Copies a file or directory from the specified location in the host file system into the specified OS image or directory\&. Expects three arguments: a path to an image file or directory, a source path (relative to the current working directory, or an absolute path, both outside of the image) and a destination path (relative to the image\*(Aqs root directory)\&. If the source path is omitted or specified as dash ("\-"), the data to write is read from standard input\&. If the source path in the host file system refers to a regular file, it is copied to the destination path\&. In this case access mode, extended attributes and timestamps are copied as well, but file ownership is not\&. If the source path in the host file system refers to a directory it is copied to the destination path, recursively with all containing files and directories\&. In this case the file ownership is copied too\&.
.sp
As with
\fB\-\-mount\fR
file system checks are implicitly run before the copy operation begins\&.
.sp
Added in version 247\&.
.RE
.PP
\fB\-\-make\-archive\fR
.RS 4
Generates an archive file from the specified disk image\&. Expects two arguments: the path to the disk image and optionally the output archive file path\&. If the latter is omitted the archive is written to standard output\&. The archive file format is determined automatically from the specified output archive file name, e\&.g\&. any path suffixed with
"\&.tar\&.xz"
will result in an xz compressed UNIX tarball (if the path is omitted an uncompressed UNIX tarball is created)\&. See
\fBlibarchive\fR(3)
for a list of supported archive formats and compression schemes\&.
.sp
Added in version 256\&.
.RE
.PP
\fB\-\-discover\fR
.RS 4
Show a list of DDIs in well\-known directories\&. This will show machine, portable service and system/configuration extension disk images in the usual directories
/usr/lib/machines/,
/usr/lib/portables/,
/usr/lib/confexts/,
/var/lib/machines/,
/var/lib/portables/,
/var/lib/extensions/
and so on\&.
.sp
Added in version 253\&.
.RE
.PP
\fB\-\-validate\fR
.RS 4
Validates the partition arrangement of a disk image (DDI), and ensures it matches the image policy specified via
\fB\-\-image\-policy=\fR, if one is specified\&. This parses the partition table and probes the file systems in the image, but does not attempt to mount them (nor to set up disk encryption/authentication via LUKS/Verity)\&. It does this taking the configured image dissection policy into account\&. Since this operation does not mount file systems, this command \(en unlike all other commands implemented by this tool \(en requires no privileges other than the ability to access the specified file\&. Prints "OK" and returns zero if the image appears to be in order and matches the specified image dissection policy\&. Otherwise prints an error message and returns non\-zero\&.
.sp
Added in version 254\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-\-read\-only\fR, \fB\-r\fR
.RS 4
Operate in read\-only mode\&. By default
\fB\-\-mount\fR
will establish writable mount points\&. If this option is specified they are established in read\-only mode instead\&.
.sp
Added in version 247\&.
.RE
.PP
\fB\-\-fsck=no\fR
.RS 4
Turn off automatic file system checking\&. By default when an image is accessed for writing (by
\fB\-\-mount\fR
or
\fB\-\-copy\-to\fR) the file systems contained in the OS image are automatically checked using the appropriate
\fBfsck\fR(8)
command, in automatic fixing mode\&. This behavior may be switched off using
\fB\-\-fsck=no\fR\&.
.sp
Added in version 247\&.
.RE
.PP
\fB\-\-growfs=no\fR
.RS 4
Turn off automatic growing of accessed file systems to their partition size, if marked for that in the GPT partition table\&. By default when an image is accessed for writing (by
\fB\-\-mount\fR
or
\fB\-\-copy\-to\fR) the file systems contained in the OS image are automatically grown to their partition sizes, if bit 59 in the GPT partition flags is set for partition types that are defined by the
\m[blue]\fBDiscoverable Partitions Specification\fR\m[]\&\s-2\u[1]\d\s+2\&. This behavior may be switched off using
\fB\-\-growfs=no\fR\&. File systems are grown automatically on access if all of the following conditions are met:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
The file system is mounted writable
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
The file system currently is smaller than the partition it is contained in (and thus can be grown)
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
The image contains a GPT partition table
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
The file system is stored on a partition defined by the Discoverable Partitions Specification
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 5.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  5." 4.2
.\}
Bit 59 of the GPT partition flags for this partition is set, as per specification
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 6.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  6." 4.2
.\}
The
\fB\-\-growfs=no\fR
option is not passed\&.
.RE
.sp
Added in version 249\&.
.RE
.PP
\fB\-\-mkdir\fR
.RS 4
If combined with
\fB\-\-mount\fR
the directory to mount the OS image to is created if it is missing\&. Note that the directory is not automatically removed when the disk image is unmounted again\&.
.sp
Added in version 247\&.
.RE
.PP
\fB\-\-rmdir\fR
.RS 4
If combined with
\fB\-\-umount\fR
the specified directory where the OS image is mounted is removed after unmounting the OS image\&.
.sp
Added in version 252\&.
.RE
.PP
\fB\-\-discard=\fR
.RS 4
Takes one of
"disabled",
"loop",
"all",
"crypto"\&. If
"disabled"
the image is accessed with empty block discarding turned off\&. If
"loop"
discarding is enabled if operating on a regular file\&. If
"crypt"
discarding is enabled even on encrypted file systems\&. If
"all"
discarding is unconditionally enabled\&.
.sp
Added in version 247\&.
.RE
.PP
\fB\-\-in\-memory\fR
.RS 4
If specified an in\-memory copy of the specified disk image is used\&. This may be used to operate with write\-access on a (possibly read\-only) image, without actually modifying the original file\&. This may also be used in order to operate on a disk image without keeping the originating file system busy, in order to allow it to be unmounted\&.
.sp
Added in version 253\&.
.RE
.PP
\fB\-\-root\-hash=\fR, \fB\-\-root\-hash\-sig=\fR, \fB\-\-verity\-data=\fR
.RS 4
Configure various aspects of Verity data integrity for the OS image\&. Option
\fB\-\-root\-hash=\fR
specifies a hex\-encoded top\-level Verity hash to use for setting up the Verity integrity protection\&. Option
\fB\-\-root\-hash\-sig=\fR
specifies the path to a file containing a PKCS#7 signature for the hash\&. This signature is passed to the kernel during activation, which will match it against signature keys available in the kernel keyring\&. Option
\fB\-\-verity\-data=\fR
specifies a path to a file with the Verity data to use for the OS image, in case it is stored in a detached file\&. It is recommended to embed the Verity data directly in the image, using the Verity mechanisms in the
\m[blue]\fBDiscoverable Partitions Specification\fR\m[]\&\s-2\u[1]\d\s+2\&.
.sp
Added in version 247\&.
.RE
.PP
\fB\-\-loop\-ref=\fR
.RS 4
Configures the "reference" string the kernel shall report as backing file for the loopback block device\&. While this is supposed to be a path or filename referencing the backing file, this is not enforced and the kernel accepts arbitrary free\-form strings, chosen by the user\&. Accepts arbitrary strings up to a length of 63 characters\&. This sets the kernel\*(Aqs
"\&.lo_file_name"
field for the block device\&. Note this is distinct from the
/sys/class/block/loopX/loop/backing_file
attribute file that always reports a path referring to the actual backing file\&. The latter is subject to mount namespace translation, the former is not\&.
.sp
This setting is particularly useful in combination with the
\fB\-\-attach\fR
command, as it allows later referencing the allocated loop device via
/dev/disk/by\-loop\-ref/\&...
symlinks\&. Example: first, set up the loopback device via
\fBsystemd\-dissect attach \-\-loop\-ref=quux foo\&.raw\fR, and then reference it in a command via the specified filename:
\fBcfdisk /dev/disk/by\-loop\-ref/quux\fR\&.
.sp
Added in version 254\&.
.RE
.PP
\fB\-\-mtree\-hash=no\fR
.RS 4
If combined with
\fB\-\-mtree\fR, turns off inclusion of file hashes in the mtree output\&. This makes the
\fB\-\-mtree\fR
faster when operating on large images\&.
.sp
Added in version 254\&.
.RE
.PP
\fB\-\-image\-policy=\fR\fB\fIpolicy\fR\fR
.RS 4
Takes an image policy string as argument, as per
\fBsystemd.image-policy\fR(7)\&. The policy is enforced when operating on the disk image specified via
\fB\-\-image=\fR, see above\&. If not specified defaults to the
"*"
policy, i\&.e\&. all recognized file systems in the image are used\&.
.RE
.PP
\fB\-\-no\-pager\fR
.RS 4
Do not pipe output into a pager\&.
.RE
.PP
\fB\-\-no\-legend\fR
.RS 4
Do not print the legend, i\&.e\&. column headers and the footer with hints\&.
.RE
.PP
\fB\-\-json=\fR\fB\fIMODE\fR\fR
.RS 4
Shows output formatted as JSON\&. Expects one of
"short"
(for the shortest possible output without any redundant whitespace or line breaks),
"pretty"
(for a pretty version of the same, with indentation and line breaks) or
"off"
(to turn off JSON output, the default)\&.
.RE
.SH "EXIT STATUS"
.PP
On success, 0 is returned, a non\-zero failure code otherwise\&. If the
\fB\-\-with\fR
command is used the exit status of the invoked command is propagated\&.
.SH "INVOCATION AS /SBIN/MOUNT\&.DDI"
.PP
The
\fBsystemd\-dissect\fR
executable may be symlinked to
/sbin/mount\&.ddi\&. If invoked through that it implements
\fBmount\fR(8)\*(Aqs "external helper" interface for the (pseudo) file system type
"ddi"\&. This means conformant disk images may be mounted directly via
.sp
.if n \{\
.RS 4
.\}
.nf
# mount \-t ddi myimage\&.raw targetdir/
.fi
.if n \{\
.RE
.\}
.PP
in a fashion mostly equivalent to:
.sp
.if n \{\
.RS 4
.\}
.nf
# systemd\-dissect \-\-mount myimage\&.raw targetdir/
.fi
.if n \{\
.RE
.\}
.PP
Note that since a single DDI may contain multiple file systems it should later be unmounted with
\fBumount \-R targetdir/\fR, for recursive operation\&.
.PP
This functionality is particularly useful to mount DDIs automatically at boot via simple
/etc/fstab
entries\&. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
/path/to/myimage\&.raw /images/myimage/ ddi defaults 0 0
.fi
.if n \{\
.RE
.\}
.PP
When invoked this way the mount options
"ro",
"rw",
"discard",
"nodiscard"
map to the corresponding options listed above (i\&.e\&.
\fB\-\-read\-only\fR,
\fB\-\-discard=all\fR,
\fB\-\-discard=disabled\fR)\&. Mount options are
\fInot\fR
generically passed on to the file systems inside the images\&.
.SH "EXAMPLES"
.PP
\fBExample\ \&1.\ \&Generate a tarball from an OS disk image (\-\-with)\fR
.sp
.if n \{\
.RS 4
.\}
.nf
# systemd\-dissect \-\-with foo\&.raw tar cz \&. >foo\&.tar\&.gz
.fi
.if n \{\
.RE
.\}
.PP
or alternatively just:
.PP
\fBExample\ \&2.\ \&Generate a tarball from an OS disk image (\-\-make\-archive)\fR
.sp
.if n \{\
.RS 4
.\}
.nf
# systemd\-dissect \-\-make\-archive foo\&.raw foo\&.tar\&.gz
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1), \fBsystemd-nspawn\fR(1), \fBsystemd.exec\fR(5), \fBsystemd.v\fR(7), \m[blue]\fBDiscoverable Partitions Specification\fR\m[]\&\s-2\u[1]\d\s+2, \fBmount\fR(8), \fBumount\fR(8), \fBfdisk\fR(8)
.SH "NOTES"
.IP " 1." 4
Discoverable Partitions Specification
.RS 4
\%https://uapi-group.org/specifications/specs/discoverable_partitions_specification
.RE
