---
Checks: >
    *,
    -altera-id-dependent-backward-branch,
    -altera-unroll-loops,
    -android-cloexec-accept,
    -android-cloexec-dup,
    -android-cloexec-fopen,
    -android-cloexec-memfd-create,
    -android-cloexec-open,
    -android-cloexec-pipe,
    -bugprone-easily-swappable-parameters,
    -bugprone-implicit-widening-of-multiplication-result,
    -bugprone-macro-parentheses,
    -bugprone-reserved-identifier,
    -cert-dcl16-c,
    -cert-dcl37-c,
    -cert-dcl51-cpp,
    -cert-env33-c,
    -cert-err33-c,
    -cert-err34-c,
    -cert-msc30-c,
    -cert-msc32-c,
    -cert-msc50-cpp,
    -cert-msc51-cpp,
    -clang-analyzer-optin.portability.UnixAPI,
    -clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling,
    -clang-analyzer-security.insecureAPI.strcpy,
    -clang-analyzer-unix.Malloc,
    -clang-diagnostic-c2x-extensions,
    -concurrency-mt-unsafe,
    -cppcoreguidelines-avoid-non-const-global-variables,
    -cppcoreguidelines-init-variables,
    -google-readability-braces-around-statements,
    -hicpp-braces-around-statements,
    -hicpp-no-assembler,
    -hicpp-uppercase-literal-suffix,
    -llvm-header-guard,
    -llvmlibc-restrict-system-libc-headers,
    -misc-no-recursion,
    -modernize-macro-to-enum,
    -readability-braces-around-statements,
    -readability-function-cognitive-complexity,
    -readability-identifier-length,
    -readability-isolate-declaration,
    -readability-uppercase-literal-suffix,

WarningsAsErrors: >
    *,
    -altera-struct-pack-align,
    -bugprone-narrowing-conversions,
    -clang-diagnostic-declaration-after-statement,
    -clang-diagnostic-format,
    -clang-diagnostic-format-invalid-specifier,
    -clang-diagnostic-sign-compare,
    -clang-diagnostic-uninitialized,
    -clang-diagnostic-unused-parameter,
    -cppcoreguidelines-avoid-magic-numbers,
    -cppcoreguidelines-narrowing-conversions,
    -hicpp-multiway-paths-covered,
    -hicpp-signed-bitwise,
    -misc-unused-parameters,
    -performance-no-int-to-ptr,
    -readability-magic-numbers,
...
