.\" Copyright (c) 1993 Michael Haardt
.\" (michael@moria.de), Fri Apr 2 11:32:09 MET DST
.\" 1993
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.\" Modified by Thomas Koenig (ig25@rz.uni-karlsruhe.de) 24 Apr 1993
.\" Modified Sat Jul 24 17:28:08 1993 by Rik Faith (faith@cs.unc.edu)
.TH intro 7 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
intro \- introduction to overview and miscellany section
.SH DESCRIPTION
Section 7 of the manual provides overviews on various topics, and
describes conventions and protocols,
character set standards, the standard filesystem layout,
and miscellaneous other things.
.SH NOTES
.SS Authors and copyright conditions
Look at the header of the manual page source for the author(s) and copyright
conditions.
Note that these can be different from page to page!
.SH SEE ALSO
.BR standards (7)
