.\" Copyright (c) 2006 by Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.\" 28 Dec 2006 - Initial Creation
.\"
.TH termio 7 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
termio \- System V terminal driver interface
.SH DESCRIPTION
.B termio
is the name of the old System V terminal driver interface.
This interface defined a
.I termio
structure used to store terminal settings, and a range of
.BR ioctl (2)
operations to get and set terminal attributes.
.P
The
.B termio
interface is now obsolete: POSIX.1-1990 standardized a modified
version of this interface, under the name
.BR termios .
The POSIX.1 data structure differs slightly from the
System V version, and POSIX.1 defined a suite of functions
to replace the various
.BR ioctl (2)
operations that existed in System V.
(This was done because
.BR ioctl (2)
was unstandardized, and its variadic third argument
does not allow argument type checking.)
.P
If you're looking for a page called "termio", then you can probably
find most of the information that you seek in either
.BR termios (3)
or
.BR ioctl_tty (2).
.SH SEE ALSO
.BR reset (1),
.BR setterm (1),
.BR stty (1),
.BR ioctl_tty (2),
.BR termios (3),
.BR tty (4)
