.\" Copyright (C) 2014 Red Hat, Inc. All Rights Reserved.
.\" Written by David Howells (dhowells@redhat.com)
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.TH thread-keyring 7 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
thread-keyring \- per-thread keyring
.SH DESCRIPTION
The thread keyring is a keyring used to anchor keys on behalf of a process.
It is created only when a thread requests it.
The thread keyring has the name (description)
.IR _tid .
.P
A special serial number value,
.BR KEY_SPEC_THREAD_KEYRING ,
is defined that can be used in lieu of the actual serial number of
the calling thread's thread keyring.
.P
From the
.BR keyctl (1)
utility, '\fB@t\fP' can be used instead of a numeric key ID in
much the same way, but as
.BR keyctl (1)
is a program run after forking, this is of no utility.
.P
Thread keyrings are not inherited across
.BR clone (2)
and
.BR fork (2)
and are cleared by
.BR execve (2).
A thread keyring is destroyed when the thread that refers to it terminates.
.P
Initially, a thread does not have a thread keyring.
If a thread doesn't have a thread keyring when it is accessed,
then it will be created if it is to be modified;
otherwise the operation fails with the error
.BR ENOKEY .
.SH SEE ALSO
.ad l
.nh
.BR keyctl (1),
.BR keyctl (3),
.BR keyrings (7),
.BR persistent\-keyring (7),
.BR process\-keyring (7),
.BR session\-keyring (7),
.BR user\-keyring (7),
.BR user\-session\-keyring (7)
