.\" Copyright (c) 2019 by Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.\"
.TH uts_namespaces 7 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
uts_namespaces \- overview of Linux UTS namespaces
.SH DESCRIPTION
UTS namespaces provide isolation of two system identifiers:
the hostname and the NIS domain name.
These identifiers are set using
.BR sethostname (2)
and
.BR setdomainname (2),
and can be retrieved using
.BR uname (2),
.BR gethostname (2),
and
.BR getdomainname (2).
Changes made to these identifiers are visible to all other
processes in the same UTS namespace,
but are not visible to processes in other UTS namespaces.
.P
When a process creates a new UTS namespace using
.BR clone (2)
or
.BR unshare (2)
with the
.B CLONE_NEWUTS
flag, the hostname and domain name of the new UTS namespace are copied
from the corresponding values in the caller's UTS namespace.
.P
Use of UTS namespaces requires a kernel that is configured with the
.B CONFIG_UTS_NS
option.
.SH SEE ALSO
.BR nsenter (1),
.BR unshare (1),
.BR clone (2),
.BR getdomainname (2),
.BR gethostname (2),
.BR setns (2),
.BR uname (2),
.BR unshare (2),
.BR namespaces (7)
