.\" Copyright (c) 1993 Michael Haardt (michael@moria.de),
.\"     Fri Apr  2 11:32:09 MET DST 1993
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.\" Modified Sat Jul 24 16:57:14 1993 by Rik Faith (faith@cs.unc.edu)
.TH intro 4 2024-05-02 "Linux man-pages (unreleased)"
.SH NAME
intro \- introduction to special files
.SH DESCRIPTION
Section 4 of the manual describes special files (devices).
.SH FILES
/dev/* \[em] device files
.SH NOTES
.SS Authors and copyright conditions
Look at the header of the manual page source for the author(s) and copyright
conditions.
Note that these can be different from page to page!
.SH SEE ALSO
.BR mknod (1),
.BR mknod (2),
.BR standards (7)
